/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.Cnta;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CntaRecord extends UpdatableRecordImpl<CntaRecord> implements Record5<Integer, String, Double, Double, Double> {

    private static final long serialVersionUID = 2015172352;

    /**
     * Setter for <code>CNTA.CNTA_ID</code>.
     */
    public void setCntaId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>CNTA.CNTA_ID</code>.
     */
    public Integer getCntaId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>CNTA.CNTA_NAME</code>.
     */
    public void setCntaName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CNTA.CNTA_NAME</code>.
     */
    public String getCntaName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CNTA.CNTA_PARAM1</code>.
     */
    public void setCntaParam1(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>CNTA.CNTA_PARAM1</code>.
     */
    public Double getCntaParam1() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>CNTA.CNTA_PARAM2</code>.
     */
    public void setCntaParam2(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>CNTA.CNTA_PARAM2</code>.
     */
    public Double getCntaParam2() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>CNTA.CNTA_PARAM3</code>.
     */
    public void setCntaParam3(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>CNTA.CNTA_PARAM3</code>.
     */
    public Double getCntaParam3() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Double, Double, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Double, Double, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Cnta.CNTA.CNTA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Cnta.CNTA.CNTA_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Cnta.CNTA.CNTA_PARAM1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Cnta.CNTA.CNTA_PARAM2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Cnta.CNTA.CNTA_PARAM3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCntaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCntaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getCntaParam1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getCntaParam2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getCntaParam3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCntaId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCntaName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getCntaParam1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getCntaParam2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getCntaParam3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntaRecord value1(Integer value) {
        setCntaId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntaRecord value2(String value) {
        setCntaName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntaRecord value3(Double value) {
        setCntaParam1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntaRecord value4(Double value) {
        setCntaParam2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntaRecord value5(Double value) {
        setCntaParam3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntaRecord values(Integer value1, String value2, Double value3, Double value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CntaRecord
     */
    public CntaRecord() {
        super(Cnta.CNTA);
    }

    /**
     * Create a detached, initialised CntaRecord
     */
    public CntaRecord(Integer cntaId, String cntaName, Double cntaParam1, Double cntaParam2, Double cntaParam3) {
        super(Cnta.CNTA);

        set(0, cntaId);
        set(1, cntaName);
        set(2, cntaParam1);
        set(3, cntaParam2);
        set(4, cntaParam3);
    }
}
