/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.CntExtValues;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CntExtValuesRecord extends UpdatableRecordImpl<CntExtValuesRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = -2016049229;

    /**
     * Setter for <code>CNT_EXT_VALUES.CNT_ID</code>.
     */
    public void setCntId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>CNT_EXT_VALUES.CNT_ID</code>.
     */
    public Integer getCntId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>CNT_EXT_VALUES.PARAM_ID</code>.
     */
    public void setParamId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>CNT_EXT_VALUES.PARAM_ID</code>.
     */
    public Integer getParamId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>CNT_EXT_VALUES.PARAM_VALUE</code>.
     */
    public void setParamValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CNT_EXT_VALUES.PARAM_VALUE</code>.
     */
    public String getParamValue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CntExtValues.CNT_EXT_VALUES.CNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CntExtValues.CNT_EXT_VALUES.PARAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CntExtValues.CNT_EXT_VALUES.PARAM_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCntId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getParamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getParamValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCntId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getParamId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getParamValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntExtValuesRecord value1(Integer value) {
        setCntId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntExtValuesRecord value2(Integer value) {
        setParamId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntExtValuesRecord value3(String value) {
        setParamValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntExtValuesRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CntExtValuesRecord
     */
    public CntExtValuesRecord() {
        super(CntExtValues.CNT_EXT_VALUES);
    }

    /**
     * Create a detached, initialised CntExtValuesRecord
     */
    public CntExtValuesRecord(Integer cntId, Integer paramId, String paramValue) {
        super(CntExtValues.CNT_EXT_VALUES);

        set(0, cntId);
        set(1, paramId);
        set(2, paramValue);
    }
}
