/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.CntSync;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CntSyncRecord extends TableRecordImpl<CntSyncRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -399974280;

    /**
     * Setter for <code>CNT_SYNC.CNT_ID</code>.
     */
    public void setCntId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>CNT_SYNC.CNT_ID</code>.
     */
    public Integer getCntId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>CNT_SYNC.CNTB_TYPE</code>.
     */
    public void setCntbType(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>CNT_SYNC.CNTB_TYPE</code>.
     */
    public Integer getCntbType() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>CNT_SYNC.CNT_LAST_EXT_ID</code>.
     */
    public void setCntLastExtId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>CNT_SYNC.CNT_LAST_EXT_ID</code>.
     */
    public Integer getCntLastExtId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>CNT_SYNC.CNT_LOG_SYNC</code>.
     */
    public void setCntLogSync(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>CNT_SYNC.CNT_LOG_SYNC</code>.
     */
    public Integer getCntLogSync() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CntSync.CNT_SYNC.CNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CntSync.CNT_SYNC.CNTB_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CntSync.CNT_SYNC.CNT_LAST_EXT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return CntSync.CNT_SYNC.CNT_LOG_SYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCntId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCntbType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCntLastExtId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCntLogSync();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCntId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCntbType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCntLastExtId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCntLogSync();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntSyncRecord value1(Integer value) {
        setCntId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntSyncRecord value2(Integer value) {
        setCntbType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntSyncRecord value3(Integer value) {
        setCntLastExtId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntSyncRecord value4(Integer value) {
        setCntLogSync(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntSyncRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CntSyncRecord
     */
    public CntSyncRecord() {
        super(CntSync.CNT_SYNC);
    }

    /**
     * Create a detached, initialised CntSyncRecord
     */
    public CntSyncRecord(Integer cntId, Integer cntbType, Integer cntLastExtId, Integer cntLogSync) {
        super(CntSync.CNT_SYNC);

        set(0, cntId);
        set(1, cntbType);
        set(2, cntLastExtId);
        set(3, cntLogSync);
    }
}
