/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.GetCntControl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetCntControlRecord extends TableRecordImpl<GetCntControlRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1603907241;

    /**
     * Setter for <code>GET_CNT_CONTROL.CNT_ID</code>.
     */
    public void setCntId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>GET_CNT_CONTROL.CNT_ID</code>.
     */
    public Integer getCntId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>GET_CNT_CONTROL.CNTCTRL_ACTION</code>.
     */
    public void setCntctrlAction(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>GET_CNT_CONTROL.CNTCTRL_ACTION</code>.
     */
    public Integer getCntctrlAction() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>GET_CNT_CONTROL.CNTCTRL_LIMIT</code>.
     */
    public void setCntctrlLimit(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>GET_CNT_CONTROL.CNTCTRL_LIMIT</code>.
     */
    public Integer getCntctrlLimit() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>GET_CNT_CONTROL.CNTCTRL_SYNC</code>.
     */
    public void setCntctrlSync(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>GET_CNT_CONTROL.CNTCTRL_SYNC</code>.
     */
    public Integer getCntctrlSync() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GetCntControl.GET_CNT_CONTROL.CNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return GetCntControl.GET_CNT_CONTROL.CNTCTRL_ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GetCntControl.GET_CNT_CONTROL.CNTCTRL_LIMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return GetCntControl.GET_CNT_CONTROL.CNTCTRL_SYNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCntId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCntctrlAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCntctrlLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCntctrlSync();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCntId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCntctrlAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCntctrlLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCntctrlSync();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetCntControlRecord value1(Integer value) {
        setCntId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetCntControlRecord value2(Integer value) {
        setCntctrlAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetCntControlRecord value3(Integer value) {
        setCntctrlLimit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetCntControlRecord value4(Integer value) {
        setCntctrlSync(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetCntControlRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetCntControlRecord
     */
    public GetCntControlRecord() {
        super(GetCntControl.GET_CNT_CONTROL);
    }

    /**
     * Create a detached, initialised GetCntControlRecord
     */
    public GetCntControlRecord(Integer cntId, Integer cntctrlAction, Integer cntctrlLimit, Integer cntctrlSync) {
        super(GetCntControl.GET_CNT_CONTROL);

        set(0, cntId);
        set(1, cntctrlAction);
        set(2, cntctrlLimit);
        set(3, cntctrlSync);
    }
}
