/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.GetImpulseCntv;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetImpulseCntvRecord extends TableRecordImpl<GetImpulseCntvRecord> implements Record13<Integer, Double, Double, Double, Double, Double, Timestamp, Integer, Double, Double, Double, Double, Double> {

    private static final long serialVersionUID = -1055258661;

    /**
     * Setter for <code>GET_IMPULSE_CNTV.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.VALUE1</code>.
     */
    public void setValue1(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.VALUE1</code>.
     */
    public Double getValue1() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.VALUE2</code>.
     */
    public void setValue2(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.VALUE2</code>.
     */
    public Double getValue2() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.VALUE3</code>.
     */
    public void setValue3(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.VALUE3</code>.
     */
    public Double getValue3() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.VALUE4</code>.
     */
    public void setValue4(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.VALUE4</code>.
     */
    public Double getValue4() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.VALUE5</code>.
     */
    public void setValue5(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.VALUE5</code>.
     */
    public Double getValue5() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.CDATE</code>.
     */
    public void setCdate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.CDATE</code>.
     */
    public Timestamp getCdate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.STATE</code>.
     */
    public void setState(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.STATE</code>.
     */
    public Integer getState() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.VALUE6</code>.
     */
    public void setValue6(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.VALUE6</code>.
     */
    public Double getValue6() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.VALUE7</code>.
     */
    public void setValue7(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.VALUE7</code>.
     */
    public Double getValue7() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.VALUE8</code>.
     */
    public void setValue8(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.VALUE8</code>.
     */
    public Double getValue8() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.VALUE9</code>.
     */
    public void setValue9(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.VALUE9</code>.
     */
    public Double getValue9() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>GET_IMPULSE_CNTV.VALUE10</code>.
     */
    public void setValue10(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>GET_IMPULSE_CNTV.VALUE10</code>.
     */
    public Double getValue10() {
        return (Double) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Double, Double, Double, Double, Double, Timestamp, Integer, Double, Double, Double, Double, Double> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Double, Double, Double, Double, Double, Timestamp, Integer, Double, Double, Double, Double, Double> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field2() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.VALUE1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.VALUE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.VALUE3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.VALUE4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.VALUE5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.CDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.VALUE6;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field10() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.VALUE7;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field11() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.VALUE8;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field12() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.VALUE9;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field13() {
        return GetImpulseCntv.GET_IMPULSE_CNTV.VALUE10;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component2() {
        return getValue1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getValue2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getValue3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getValue4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getValue5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component9() {
        return getValue6();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component10() {
        return getValue7();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component11() {
        return getValue8();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component12() {
        return getValue9();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component13() {
        return getValue10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value2() {
        return getValue1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getValue2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getValue3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getValue4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getValue5();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getValue6();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value10() {
        return getValue7();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value11() {
        return getValue8();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value12() {
        return getValue9();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value13() {
        return getValue10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value2(Double value) {
        setValue1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value3(Double value) {
        setValue2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value4(Double value) {
        setValue3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value5(Double value) {
        setValue4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value6(Double value) {
        setValue5(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value7(Timestamp value) {
        setCdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value8(Integer value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value9(Double value) {
        setValue6(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value10(Double value) {
        setValue7(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value11(Double value) {
        setValue8(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value12(Double value) {
        setValue9(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord value13(Double value) {
        setValue10(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvRecord values(Integer value1, Double value2, Double value3, Double value4, Double value5, Double value6, Timestamp value7, Integer value8, Double value9, Double value10, Double value11, Double value12, Double value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetImpulseCntvRecord
     */
    public GetImpulseCntvRecord() {
        super(GetImpulseCntv.GET_IMPULSE_CNTV);
    }

    /**
     * Create a detached, initialised GetImpulseCntvRecord
     */
    public GetImpulseCntvRecord(Integer id, Double value1, Double value2, Double value3, Double value4, Double value5, Timestamp cdate, Integer state, Double value6, Double value7, Double value8, Double value9, Double value10) {
        super(GetImpulseCntv.GET_IMPULSE_CNTV);

        set(0, id);
        set(1, value1);
        set(2, value2);
        set(3, value3);
        set(4, value4);
        set(5, value5);
        set(6, cdate);
        set(7, state);
        set(8, value6);
        set(9, value7);
        set(10, value8);
        set(11, value9);
        set(12, value10);
    }
}
