/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.GetPkeTimes;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetPkeTimesRecord extends TableRecordImpl<GetPkeTimesRecord> implements Record10<String, Float, Float, Float, Float, Float, Float, Float, Float, Integer> {

    private static final long serialVersionUID = 1573617641;

    /**
     * Setter for <code>GET_PKE_TIMES.PKE_TIME_DESCR</code>.
     */
    public void setPkeTimeDescr(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GET_PKE_TIMES.PKE_TIME_DESCR</code>.
     */
    public String getPkeTimeDescr() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GET_PKE_TIMES.PKE_TIME_PHASE1</code>.
     */
    public void setPkeTimePhase1(Float value) {
        set(1, value);
    }

    /**
     * Getter for <code>GET_PKE_TIMES.PKE_TIME_PHASE1</code>.
     */
    public Float getPkeTimePhase1() {
        return (Float) get(1);
    }

    /**
     * Setter for <code>GET_PKE_TIMES.PKE_TIME_PHASE2</code>.
     */
    public void setPkeTimePhase2(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>GET_PKE_TIMES.PKE_TIME_PHASE2</code>.
     */
    public Float getPkeTimePhase2() {
        return (Float) get(2);
    }

    /**
     * Setter for <code>GET_PKE_TIMES.PKE_TIME_PHASE3</code>.
     */
    public void setPkeTimePhase3(Float value) {
        set(3, value);
    }

    /**
     * Getter for <code>GET_PKE_TIMES.PKE_TIME_PHASE3</code>.
     */
    public Float getPkeTimePhase3() {
        return (Float) get(3);
    }

    /**
     * Setter for <code>GET_PKE_TIMES.PKE_TIME_FREQ</code>.
     */
    public void setPkeTimeFreq(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>GET_PKE_TIMES.PKE_TIME_FREQ</code>.
     */
    public Float getPkeTimeFreq() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>GET_PKE_TIMES.PKE_PERC_PHASE1</code>.
     */
    public void setPkePercPhase1(Float value) {
        set(5, value);
    }

    /**
     * Getter for <code>GET_PKE_TIMES.PKE_PERC_PHASE1</code>.
     */
    public Float getPkePercPhase1() {
        return (Float) get(5);
    }

    /**
     * Setter for <code>GET_PKE_TIMES.PKE_PERC_PHASE2</code>.
     */
    public void setPkePercPhase2(Float value) {
        set(6, value);
    }

    /**
     * Getter for <code>GET_PKE_TIMES.PKE_PERC_PHASE2</code>.
     */
    public Float getPkePercPhase2() {
        return (Float) get(6);
    }

    /**
     * Setter for <code>GET_PKE_TIMES.PKE_PERC_PHASE3</code>.
     */
    public void setPkePercPhase3(Float value) {
        set(7, value);
    }

    /**
     * Getter for <code>GET_PKE_TIMES.PKE_PERC_PHASE3</code>.
     */
    public Float getPkePercPhase3() {
        return (Float) get(7);
    }

    /**
     * Setter for <code>GET_PKE_TIMES.PKE_PERC_FREQ</code>.
     */
    public void setPkePercFreq(Float value) {
        set(8, value);
    }

    /**
     * Getter for <code>GET_PKE_TIMES.PKE_PERC_FREQ</code>.
     */
    public Float getPkePercFreq() {
        return (Float) get(8);
    }

    /**
     * Setter for <code>GET_PKE_TIMES.PKE_COLOR</code>.
     */
    public void setPkeColor(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>GET_PKE_TIMES.PKE_COLOR</code>.
     */
    public Integer getPkeColor() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, Float, Float, Float, Float, Float, Float, Float, Float, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, Float, Float, Float, Float, Float, Float, Float, Float, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GetPkeTimes.GET_PKE_TIMES.PKE_TIME_DESCR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field2() {
        return GetPkeTimes.GET_PKE_TIMES.PKE_TIME_PHASE1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field3() {
        return GetPkeTimes.GET_PKE_TIMES.PKE_TIME_PHASE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field4() {
        return GetPkeTimes.GET_PKE_TIMES.PKE_TIME_PHASE3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field5() {
        return GetPkeTimes.GET_PKE_TIMES.PKE_TIME_FREQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field6() {
        return GetPkeTimes.GET_PKE_TIMES.PKE_PERC_PHASE1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field7() {
        return GetPkeTimes.GET_PKE_TIMES.PKE_PERC_PHASE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field8() {
        return GetPkeTimes.GET_PKE_TIMES.PKE_PERC_PHASE3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field9() {
        return GetPkeTimes.GET_PKE_TIMES.PKE_PERC_FREQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return GetPkeTimes.GET_PKE_TIMES.PKE_COLOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getPkeTimeDescr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component2() {
        return getPkeTimePhase1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component3() {
        return getPkeTimePhase2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component4() {
        return getPkeTimePhase3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component5() {
        return getPkeTimeFreq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component6() {
        return getPkePercPhase1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component7() {
        return getPkePercPhase2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component8() {
        return getPkePercPhase3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component9() {
        return getPkePercFreq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getPkeColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPkeTimeDescr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value2() {
        return getPkeTimePhase1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value3() {
        return getPkeTimePhase2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value4() {
        return getPkeTimePhase3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value5() {
        return getPkeTimeFreq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value6() {
        return getPkePercPhase1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value7() {
        return getPkePercPhase2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value8() {
        return getPkePercPhase3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value9() {
        return getPkePercFreq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPkeColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetPkeTimesRecord value1(String value) {
        setPkeTimeDescr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetPkeTimesRecord value2(Float value) {
        setPkeTimePhase1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetPkeTimesRecord value3(Float value) {
        setPkeTimePhase2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetPkeTimesRecord value4(Float value) {
        setPkeTimePhase3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetPkeTimesRecord value5(Float value) {
        setPkeTimeFreq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetPkeTimesRecord value6(Float value) {
        setPkePercPhase1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetPkeTimesRecord value7(Float value) {
        setPkePercPhase2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetPkeTimesRecord value8(Float value) {
        setPkePercPhase3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetPkeTimesRecord value9(Float value) {
        setPkePercFreq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetPkeTimesRecord value10(Integer value) {
        setPkeColor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetPkeTimesRecord values(String value1, Float value2, Float value3, Float value4, Float value5, Float value6, Float value7, Float value8, Float value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GetPkeTimesRecord
     */
    public GetPkeTimesRecord() {
        super(GetPkeTimes.GET_PKE_TIMES);
    }

    /**
     * Create a detached, initialised GetPkeTimesRecord
     */
    public GetPkeTimesRecord(String pkeTimeDescr, Float pkeTimePhase1, Float pkeTimePhase2, Float pkeTimePhase3, Float pkeTimeFreq, Float pkePercPhase1, Float pkePercPhase2, Float pkePercPhase3, Float pkePercFreq, Integer pkeColor) {
        super(GetPkeTimes.GET_PKE_TIMES);

        set(0, pkeTimeDescr);
        set(1, pkeTimePhase1);
        set(2, pkeTimePhase2);
        set(3, pkeTimePhase3);
        set(4, pkeTimeFreq);
        set(5, pkePercPhase1);
        set(6, pkePercPhase2);
        set(7, pkePercPhase3);
        set(8, pkePercFreq);
        set(9, pkeColor);
    }
}
