/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.GuardPinLog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuardPinLogRecord extends UpdatableRecordImpl<GuardPinLogRecord> implements Record11<Integer, Integer, Integer, Double, Integer, Integer, Timestamp, Timestamp, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1479229561;

    /**
     * Setter for <code>GUARD_PIN_LOG.GPLG_ID</code>.
     */
    public void setGplgId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>GUARD_PIN_LOG.GPLG_ID</code>.
     */
    public Integer getGplgId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>GUARD_PIN_LOG.GPLG_PIN_ID</code>.
     */
    public void setGplgPinId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>GUARD_PIN_LOG.GPLG_PIN_ID</code>.
     */
    public Integer getGplgPinId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>GUARD_PIN_LOG.GPLG_TYPE</code>.
     */
    public void setGplgType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>GUARD_PIN_LOG.GPLG_TYPE</code>.
     */
    public Integer getGplgType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>GUARD_PIN_LOG.GPLG_AVALUE</code>.
     */
    public void setGplgAvalue(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>GUARD_PIN_LOG.GPLG_AVALUE</code>.
     */
    public Double getGplgAvalue() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>GUARD_PIN_LOG.GPLG_DVALUE</code>.
     */
    public void setGplgDvalue(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>GUARD_PIN_LOG.GPLG_DVALUE</code>.
     */
    public Integer getGplgDvalue() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>GUARD_PIN_LOG.GPLG_STATE</code>.
     */
    public void setGplgState(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>GUARD_PIN_LOG.GPLG_STATE</code>.
     */
    public Integer getGplgState() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>GUARD_PIN_LOG.GPLG_LDATE</code>.
     */
    public void setGplgLdate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>GUARD_PIN_LOG.GPLG_LDATE</code>.
     */
    public Timestamp getGplgLdate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>GUARD_PIN_LOG.GPLG_SDATE</code>.
     */
    public void setGplgSdate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>GUARD_PIN_LOG.GPLG_SDATE</code>.
     */
    public Timestamp getGplgSdate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>GUARD_PIN_LOG.GPLG_USK_ID</code>.
     */
    public void setGplgUskId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>GUARD_PIN_LOG.GPLG_USK_ID</code>.
     */
    public Integer getGplgUskId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>GUARD_PIN_LOG.GPLG_EVENT</code>.
     */
    public void setGplgEvent(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>GUARD_PIN_LOG.GPLG_EVENT</code>.
     */
    public Integer getGplgEvent() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>GUARD_PIN_LOG.GPLG_ACTION</code>.
     */
    public void setGplgAction(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>GUARD_PIN_LOG.GPLG_ACTION</code>.
     */
    public Integer getGplgAction() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Integer, Double, Integer, Integer, Timestamp, Timestamp, Integer, Integer, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Integer, Double, Integer, Integer, Timestamp, Timestamp, Integer, Integer, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GuardPinLog.GUARD_PIN_LOG.GPLG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return GuardPinLog.GUARD_PIN_LOG.GPLG_PIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GuardPinLog.GUARD_PIN_LOG.GPLG_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return GuardPinLog.GUARD_PIN_LOG.GPLG_AVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return GuardPinLog.GUARD_PIN_LOG.GPLG_DVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return GuardPinLog.GUARD_PIN_LOG.GPLG_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return GuardPinLog.GUARD_PIN_LOG.GPLG_LDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return GuardPinLog.GUARD_PIN_LOG.GPLG_SDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return GuardPinLog.GUARD_PIN_LOG.GPLG_USK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return GuardPinLog.GUARD_PIN_LOG.GPLG_EVENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return GuardPinLog.GUARD_PIN_LOG.GPLG_ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getGplgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getGplgPinId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getGplgType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getGplgAvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getGplgDvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getGplgState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getGplgLdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getGplgSdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getGplgUskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getGplgEvent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getGplgAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGplgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getGplgPinId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGplgType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getGplgAvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGplgDvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getGplgState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getGplgLdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getGplgSdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getGplgUskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getGplgEvent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getGplgAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord value1(Integer value) {
        setGplgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord value2(Integer value) {
        setGplgPinId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord value3(Integer value) {
        setGplgType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord value4(Double value) {
        setGplgAvalue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord value5(Integer value) {
        setGplgDvalue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord value6(Integer value) {
        setGplgState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord value7(Timestamp value) {
        setGplgLdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord value8(Timestamp value) {
        setGplgSdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord value9(Integer value) {
        setGplgUskId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord value10(Integer value) {
        setGplgEvent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord value11(Integer value) {
        setGplgAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinLogRecord values(Integer value1, Integer value2, Integer value3, Double value4, Integer value5, Integer value6, Timestamp value7, Timestamp value8, Integer value9, Integer value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuardPinLogRecord
     */
    public GuardPinLogRecord() {
        super(GuardPinLog.GUARD_PIN_LOG);
    }

    /**
     * Create a detached, initialised GuardPinLogRecord
     */
    public GuardPinLogRecord(Integer gplgId, Integer gplgPinId, Integer gplgType, Double gplgAvalue, Integer gplgDvalue, Integer gplgState, Timestamp gplgLdate, Timestamp gplgSdate, Integer gplgUskId, Integer gplgEvent, Integer gplgAction) {
        super(GuardPinLog.GUARD_PIN_LOG);

        set(0, gplgId);
        set(1, gplgPinId);
        set(2, gplgType);
        set(3, gplgAvalue);
        set(4, gplgDvalue);
        set(5, gplgState);
        set(6, gplgLdate);
        set(7, gplgSdate);
        set(8, gplgUskId);
        set(9, gplgEvent);
        set(10, gplgAction);
    }
}
