/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.GuardPin;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuardPinRecord extends UpdatableRecordImpl<GuardPinRecord> implements Record12<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 1698420846;

    /**
     * Setter for <code>GUARD_PIN.GPIN_ID</code>.
     */
    public void setGpinId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_ID</code>.
     */
    public Integer getGpinId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>GUARD_PIN.GPIN_ZID</code>.
     */
    public void setGpinZid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_ZID</code>.
     */
    public Integer getGpinZid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>GUARD_PIN.GPIN_UNK_ID</code>.
     */
    public void setGpinUnkId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_UNK_ID</code>.
     */
    public Integer getGpinUnkId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>GUARD_PIN.GPIN_TYPE</code>.
     */
    public void setGpinType(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_TYPE</code>.
     */
    public Integer getGpinType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>GUARD_PIN.GPIN_DEVTYPE</code>.
     */
    public void setGpinDevtype(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_DEVTYPE</code>.
     */
    public Integer getGpinDevtype() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>GUARD_PIN.GPIN_ENTRY</code>.
     */
    public void setGpinEntry(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_ENTRY</code>.
     */
    public Integer getGpinEntry() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>GUARD_PIN.GPIN_NETADR</code>.
     */
    public void setGpinNetadr(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_NETADR</code>.
     */
    public Integer getGpinNetadr() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>GUARD_PIN.GPIN_NAME</code>.
     */
    public void setGpinName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_NAME</code>.
     */
    public String getGpinName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>GUARD_PIN.GPIN_DELAY</code>.
     */
    public void setGpinDelay(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_DELAY</code>.
     */
    public Integer getGpinDelay() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>GUARD_PIN.GPIN_ATYPE</code>.
     */
    public void setGpinAtype(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_ATYPE</code>.
     */
    public Integer getGpinAtype() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>GUARD_PIN.GPIN_ON</code>.
     */
    public void setGpinOn(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_ON</code>.
     */
    public Integer getGpinOn() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>GUARD_PIN.GPIN_REM</code>.
     */
    public void setGpinRem(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>GUARD_PIN.GPIN_REM</code>.
     */
    public String getGpinRem() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GuardPin.GUARD_PIN.GPIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return GuardPin.GUARD_PIN.GPIN_ZID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GuardPin.GUARD_PIN.GPIN_UNK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return GuardPin.GUARD_PIN.GPIN_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return GuardPin.GUARD_PIN.GPIN_DEVTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return GuardPin.GUARD_PIN.GPIN_ENTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return GuardPin.GUARD_PIN.GPIN_NETADR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return GuardPin.GUARD_PIN.GPIN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return GuardPin.GUARD_PIN.GPIN_DELAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return GuardPin.GUARD_PIN.GPIN_ATYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return GuardPin.GUARD_PIN.GPIN_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return GuardPin.GUARD_PIN.GPIN_REM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getGpinId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getGpinZid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getGpinUnkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getGpinType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getGpinDevtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getGpinEntry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getGpinNetadr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getGpinName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getGpinDelay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getGpinAtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getGpinOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getGpinRem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGpinId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getGpinZid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGpinUnkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getGpinType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGpinDevtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getGpinEntry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getGpinNetadr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getGpinName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getGpinDelay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getGpinAtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getGpinOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getGpinRem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value1(Integer value) {
        setGpinId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value2(Integer value) {
        setGpinZid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value3(Integer value) {
        setGpinUnkId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value4(Integer value) {
        setGpinType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value5(Integer value) {
        setGpinDevtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value6(Integer value) {
        setGpinEntry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value7(Integer value) {
        setGpinNetadr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value8(String value) {
        setGpinName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value9(Integer value) {
        setGpinDelay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value10(Integer value) {
        setGpinAtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value11(Integer value) {
        setGpinOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord value12(String value) {
        setGpinRem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardPinRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, String value8, Integer value9, Integer value10, Integer value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuardPinRecord
     */
    public GuardPinRecord() {
        super(GuardPin.GUARD_PIN);
    }

    /**
     * Create a detached, initialised GuardPinRecord
     */
    public GuardPinRecord(Integer gpinId, Integer gpinZid, Integer gpinUnkId, Integer gpinType, Integer gpinDevtype, Integer gpinEntry, Integer gpinNetadr, String gpinName, Integer gpinDelay, Integer gpinAtype, Integer gpinOn, String gpinRem) {
        super(GuardPin.GUARD_PIN);

        set(0, gpinId);
        set(1, gpinZid);
        set(2, gpinUnkId);
        set(3, gpinType);
        set(4, gpinDevtype);
        set(5, gpinEntry);
        set(6, gpinNetadr);
        set(7, gpinName);
        set(8, gpinDelay);
        set(9, gpinAtype);
        set(10, gpinOn);
        set(11, gpinRem);
    }
}
