/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.GuardLine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuardLineRecord extends UpdatableRecordImpl<GuardLineRecord> implements Record11<Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 196063074;

    /**
     * Setter for <code>GUARD_LINE.GRDL_ID</code>.
     */
    public void setGrdlId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>GUARD_LINE.GRDL_ID</code>.
     */
    public Integer getGrdlId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>GUARD_LINE.GRDL_ZID</code>.
     */
    public void setGrdlZid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>GUARD_LINE.GRDL_ZID</code>.
     */
    public Integer getGrdlZid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>GUARD_LINE.GRDL_NAME</code>.
     */
    public void setGrdlName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>GUARD_LINE.GRDL_NAME</code>.
     */
    public String getGrdlName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>GUARD_LINE.GRDL_TYPE</code>.
     */
    public void setGrdlType(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>GUARD_LINE.GRDL_TYPE</code>.
     */
    public Integer getGrdlType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>GUARD_LINE.GRDL_UNK_ID</code>.
     */
    public void setGrdlUnkId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>GUARD_LINE.GRDL_UNK_ID</code>.
     */
    public Integer getGrdlUnkId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>GUARD_LINE.GRDL_NUM</code>.
     */
    public void setGrdlNum(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>GUARD_LINE.GRDL_NUM</code>.
     */
    public Integer getGrdlNum() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>GUARD_LINE.GRDL_ON</code>.
     */
    public void setGrdlOn(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>GUARD_LINE.GRDL_ON</code>.
     */
    public Integer getGrdlOn() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>GUARD_LINE.GRDL_PRIORITY</code>.
     */
    public void setGrdlPriority(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>GUARD_LINE.GRDL_PRIORITY</code>.
     */
    public Integer getGrdlPriority() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>GUARD_LINE.GRDL_DELAY</code>.
     */
    public void setGrdlDelay(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>GUARD_LINE.GRDL_DELAY</code>.
     */
    public Integer getGrdlDelay() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>GUARD_LINE.GRDL_REM</code>.
     */
    public void setGrdlRem(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>GUARD_LINE.GRDL_REM</code>.
     */
    public String getGrdlRem() {
        return (String) get(9);
    }

    /**
     * Setter for <code>GUARD_LINE.GRDL_EXMODULE</code>.
     */
    public void setGrdlExmodule(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>GUARD_LINE.GRDL_EXMODULE</code>.
     */
    public Integer getGrdlExmodule() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, String, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GuardLine.GUARD_LINE.GRDL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return GuardLine.GUARD_LINE.GRDL_ZID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GuardLine.GUARD_LINE.GRDL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return GuardLine.GUARD_LINE.GRDL_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return GuardLine.GUARD_LINE.GRDL_UNK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return GuardLine.GUARD_LINE.GRDL_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return GuardLine.GUARD_LINE.GRDL_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return GuardLine.GUARD_LINE.GRDL_PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return GuardLine.GUARD_LINE.GRDL_DELAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return GuardLine.GUARD_LINE.GRDL_REM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return GuardLine.GUARD_LINE.GRDL_EXMODULE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getGrdlId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getGrdlZid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getGrdlName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getGrdlType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getGrdlUnkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getGrdlNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getGrdlOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getGrdlPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getGrdlDelay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getGrdlRem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getGrdlExmodule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGrdlId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getGrdlZid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGrdlName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getGrdlType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGrdlUnkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getGrdlNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getGrdlOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getGrdlPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getGrdlDelay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getGrdlRem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getGrdlExmodule();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord value1(Integer value) {
        setGrdlId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord value2(Integer value) {
        setGrdlZid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord value3(String value) {
        setGrdlName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord value4(Integer value) {
        setGrdlType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord value5(Integer value) {
        setGrdlUnkId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord value6(Integer value) {
        setGrdlNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord value7(Integer value) {
        setGrdlOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord value8(Integer value) {
        setGrdlPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord value9(Integer value) {
        setGrdlDelay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord value10(String value) {
        setGrdlRem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord value11(Integer value) {
        setGrdlExmodule(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLineRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, String value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuardLineRecord
     */
    public GuardLineRecord() {
        super(GuardLine.GUARD_LINE);
    }

    /**
     * Create a detached, initialised GuardLineRecord
     */
    public GuardLineRecord(Integer grdlId, Integer grdlZid, String grdlName, Integer grdlType, Integer grdlUnkId, Integer grdlNum, Integer grdlOn, Integer grdlPriority, Integer grdlDelay, String grdlRem, Integer grdlExmodule) {
        super(GuardLine.GUARD_LINE);

        set(0, grdlId);
        set(1, grdlZid);
        set(2, grdlName);
        set(3, grdlType);
        set(4, grdlUnkId);
        set(5, grdlNum);
        set(6, grdlOn);
        set(7, grdlPriority);
        set(8, grdlDelay);
        set(9, grdlRem);
        set(10, grdlExmodule);
    }
}
