/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.Normative;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NormativeRecord extends UpdatableRecordImpl<NormativeRecord> implements Record7<Integer, String, String, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -184769080;

    /**
     * Setter for <code>NORMATIVE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>NORMATIVE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>NORMATIVE.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>NORMATIVE.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>NORMATIVE.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>NORMATIVE.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>NORMATIVE.CNT_ATYPE</code>.
     */
    public void setCntAtype(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>NORMATIVE.CNT_ATYPE</code>.
     */
    public Integer getCntAtype() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>NORMATIVE.ABONENT_ID</code>.
     */
    public void setAbonentId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>NORMATIVE.ABONENT_ID</code>.
     */
    public Integer getAbonentId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>NORMATIVE.DAY_FIRST_HOUR</code>.
     */
    public void setDayFirstHour(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>NORMATIVE.DAY_FIRST_HOUR</code>.
     */
    public Integer getDayFirstHour() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>NORMATIVE.NIGHT_FIRST_HOUR</code>.
     */
    public void setNightFirstHour(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>NORMATIVE.NIGHT_FIRST_HOUR</code>.
     */
    public Integer getNightFirstHour() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Normative.NORMATIVE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Normative.NORMATIVE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Normative.NORMATIVE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Normative.NORMATIVE.CNT_ATYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Normative.NORMATIVE.ABONENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Normative.NORMATIVE.DAY_FIRST_HOUR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Normative.NORMATIVE.NIGHT_FIRST_HOUR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCntAtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getAbonentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getDayFirstHour();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getNightFirstHour();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCntAtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getAbonentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDayFirstHour();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getNightFirstHour();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NormativeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NormativeRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NormativeRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NormativeRecord value4(Integer value) {
        setCntAtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NormativeRecord value5(Integer value) {
        setAbonentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NormativeRecord value6(Integer value) {
        setDayFirstHour(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NormativeRecord value7(Integer value) {
        setNightFirstHour(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NormativeRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NormativeRecord
     */
    public NormativeRecord() {
        super(Normative.NORMATIVE);
    }

    /**
     * Create a detached, initialised NormativeRecord
     */
    public NormativeRecord(Integer id, String name, String description, Integer cntAtype, Integer abonentId, Integer dayFirstHour, Integer nightFirstHour) {
        super(Normative.NORMATIVE);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, cntAtype);
        set(4, abonentId);
        set(5, dayFirstHour);
        set(6, nightFirstHour);
    }
}
