/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.ObjActionAvailableGet;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ObjActionAvailableGetRecord extends TableRecordImpl<ObjActionAvailableGetRecord> implements Record5<Integer, Integer, Integer, String, String> {

    private static final long serialVersionUID = -1612721217;

    /**
     * Setter for <code>OBJ_ACTION_AVAILABLE_GET.OBJ_ID_OUT</code>.
     */
    public void setObjIdOut(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>OBJ_ACTION_AVAILABLE_GET.OBJ_ID_OUT</code>.
     */
    public Integer getObjIdOut() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>OBJ_ACTION_AVAILABLE_GET.OBJ_ACTION</code>.
     */
    public void setObjAction(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>OBJ_ACTION_AVAILABLE_GET.OBJ_ACTION</code>.
     */
    public Integer getObjAction() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>OBJ_ACTION_AVAILABLE_GET.OBJ_ACTION_TYPE</code>.
     */
    public void setObjActionType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>OBJ_ACTION_AVAILABLE_GET.OBJ_ACTION_TYPE</code>.
     */
    public Integer getObjActionType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>OBJ_ACTION_AVAILABLE_GET.OBJ_ACTION_NAME</code>.
     */
    public void setObjActionName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>OBJ_ACTION_AVAILABLE_GET.OBJ_ACTION_NAME</code>.
     */
    public String getObjActionName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>OBJ_ACTION_AVAILABLE_GET.OBJ_COMMENT</code>.
     */
    public void setObjComment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>OBJ_ACTION_AVAILABLE_GET.OBJ_COMMENT</code>.
     */
    public String getObjComment() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ObjActionAvailableGet.OBJ_ACTION_AVAILABLE_GET.OBJ_ID_OUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ObjActionAvailableGet.OBJ_ACTION_AVAILABLE_GET.OBJ_ACTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ObjActionAvailableGet.OBJ_ACTION_AVAILABLE_GET.OBJ_ACTION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ObjActionAvailableGet.OBJ_ACTION_AVAILABLE_GET.OBJ_ACTION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ObjActionAvailableGet.OBJ_ACTION_AVAILABLE_GET.OBJ_COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getObjIdOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getObjAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getObjActionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getObjActionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getObjComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getObjIdOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getObjAction();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getObjActionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getObjActionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getObjComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ObjActionAvailableGetRecord value1(Integer value) {
        setObjIdOut(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ObjActionAvailableGetRecord value2(Integer value) {
        setObjAction(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ObjActionAvailableGetRecord value3(Integer value) {
        setObjActionType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ObjActionAvailableGetRecord value4(String value) {
        setObjActionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ObjActionAvailableGetRecord value5(String value) {
        setObjComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ObjActionAvailableGetRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ObjActionAvailableGetRecord
     */
    public ObjActionAvailableGetRecord() {
        super(ObjActionAvailableGet.OBJ_ACTION_AVAILABLE_GET);
    }

    /**
     * Create a detached, initialised ObjActionAvailableGetRecord
     */
    public ObjActionAvailableGetRecord(Integer objIdOut, Integer objAction, Integer objActionType, String objActionName, String objComment) {
        super(ObjActionAvailableGet.OBJ_ACTION_AVAILABLE_GET);

        set(0, objIdOut);
        set(1, objAction);
        set(2, objActionType);
        set(3, objActionName);
        set(4, objComment);
    }
}
