/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import ru.smartsarov.citylighting.sprut.tables.UskExtModule;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UskExtModuleRecord extends UpdatableRecordImpl<UskExtModuleRecord> implements Record9<Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1516931251;

    /**
     * Setter for <code>USK_EXT_MODULE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>USK_EXT_MODULE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>USK_EXT_MODULE.USK_ID</code>.
     */
    public void setUskId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>USK_EXT_MODULE.USK_ID</code>.
     */
    public Integer getUskId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>USK_EXT_MODULE.MODULE_TYPE</code>.
     */
    public void setModuleType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>USK_EXT_MODULE.MODULE_TYPE</code>.
     */
    public Integer getModuleType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>USK_EXT_MODULE.NETADR</code>.
     */
    public void setNetadr(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>USK_EXT_MODULE.NETADR</code>.
     */
    public Integer getNetadr() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>USK_EXT_MODULE.COM_PORT</code>.
     */
    public void setComPort(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>USK_EXT_MODULE.COM_PORT</code>.
     */
    public Integer getComPort() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>USK_EXT_MODULE.NAME</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>USK_EXT_MODULE.NAME</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>USK_EXT_MODULE.ENABLE</code>.
     */
    public void setEnable(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>USK_EXT_MODULE.ENABLE</code>.
     */
    public Integer getEnable() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>USK_EXT_MODULE.ADR_ID</code>.
     */
    public void setAdrId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>USK_EXT_MODULE.ADR_ID</code>.
     */
    public Integer getAdrId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>USK_EXT_MODULE.LIGHTLINE</code>.
     */
    public void setLightline(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>USK_EXT_MODULE.LIGHTLINE</code>.
     */
    public Integer getLightline() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, String, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UskExtModule.USK_EXT_MODULE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UskExtModule.USK_EXT_MODULE.USK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UskExtModule.USK_EXT_MODULE.MODULE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return UskExtModule.USK_EXT_MODULE.NETADR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return UskExtModule.USK_EXT_MODULE.COM_PORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UskExtModule.USK_EXT_MODULE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return UskExtModule.USK_EXT_MODULE.ENABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return UskExtModule.USK_EXT_MODULE.ADR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return UskExtModule.USK_EXT_MODULE.LIGHTLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getModuleType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getNetadr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getComPort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getAdrId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getLightline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getModuleType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNetadr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getComPort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getAdrId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getLightline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtModuleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtModuleRecord value2(Integer value) {
        setUskId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtModuleRecord value3(Integer value) {
        setModuleType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtModuleRecord value4(Integer value) {
        setNetadr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtModuleRecord value5(Integer value) {
        setComPort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtModuleRecord value6(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtModuleRecord value7(Integer value) {
        setEnable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtModuleRecord value8(Integer value) {
        setAdrId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtModuleRecord value9(Integer value) {
        setLightline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtModuleRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UskExtModuleRecord
     */
    public UskExtModuleRecord() {
        super(UskExtModule.USK_EXT_MODULE);
    }

    /**
     * Create a detached, initialised UskExtModuleRecord
     */
    public UskExtModuleRecord(Integer id, Integer uskId, Integer moduleType, Integer netadr, Integer comPort, String name, Integer enable, Integer adrId, Integer lightline) {
        super(UskExtModule.USK_EXT_MODULE);

        set(0, id);
        set(1, uskId);
        set(2, moduleType);
        set(3, netadr);
        set(4, comPort);
        set(5, name);
        set(6, enable);
        set(7, adrId);
        set(8, lightline);
    }
}
