/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>AB_FNUM</code>
     */
    public static final Sequence<Long> AB_FNUM = new SequenceImpl<Long>("AB_FNUM", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>AB_ID</code>
     */
    public static final Sequence<Long> AB_ID = new SequenceImpl<Long>("AB_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>AB_UNUM</code>
     */
    public static final Sequence<Long> AB_UNUM = new SequenceImpl<Long>("AB_UNUM", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>ADR_ID</code>
     */
    public static final Sequence<Long> ADR_ID = new SequenceImpl<Long>("ADR_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>AT_ID</code>
     */
    public static final Sequence<Long> AT_ID = new SequenceImpl<Long>("AT_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CHANGES_CNT_ID</code>
     */
    public static final Sequence<Long> CHANGES_CNT_ID = new SequenceImpl<Long>("CHANGES_CNT_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CHANGES_GUARD_LINE_ID</code>
     */
    public static final Sequence<Long> CHANGES_GUARD_LINE_ID = new SequenceImpl<Long>("CHANGES_GUARD_LINE_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CHANGES_GUARD_PIN_ID</code>
     */
    public static final Sequence<Long> CHANGES_GUARD_PIN_ID = new SequenceImpl<Long>("CHANGES_GUARD_PIN_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CHANGES_GUARD_ZONE_ID</code>
     */
    public static final Sequence<Long> CHANGES_GUARD_ZONE_ID = new SequenceImpl<Long>("CHANGES_GUARD_ZONE_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CHANGES_USK_ID</code>
     */
    public static final Sequence<Long> CHANGES_USK_ID = new SequenceImpl<Long>("CHANGES_USK_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CITY_ID</code>
     */
    public static final Sequence<Long> CITY_ID = new SequenceImpl<Long>("CITY_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNTC_ID</code>
     */
    public static final Sequence<Long> CNTC_ID = new SequenceImpl<Long>("CNTC_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNTEL_ID</code>
     */
    public static final Sequence<Long> CNTEL_ID = new SequenceImpl<Long>("CNTEL_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNTL_ID</code>
     */
    public static final Sequence<Long> CNTL_ID = new SequenceImpl<Long>("CNTL_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNTMEL_ID</code>
     */
    public static final Sequence<Long> CNTMEL_ID = new SequenceImpl<Long>("CNTMEL_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNTMML_ID</code>
     */
    public static final Sequence<Long> CNTMML_ID = new SequenceImpl<Long>("CNTMML_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNTMPL_ID</code>
     */
    public static final Sequence<Long> CNTMPL_ID = new SequenceImpl<Long>("CNTMPL_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNTMVL_ID</code>
     */
    public static final Sequence<Long> CNTMVL_ID = new SequenceImpl<Long>("CNTMVL_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNTM_ID</code>
     */
    public static final Sequence<Long> CNTM_ID = new SequenceImpl<Long>("CNTM_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNT_EXT_PARAM_ID</code>
     */
    public static final Sequence<Long> CNT_EXT_PARAM_ID = new SequenceImpl<Long>("CNT_EXT_PARAM_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNT_GROUP_ID</code>
     */
    public static final Sequence<Long> CNT_GROUP_ID = new SequenceImpl<Long>("CNT_GROUP_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNT_HEAT_TS_ID</code>
     */
    public static final Sequence<Long> CNT_HEAT_TS_ID = new SequenceImpl<Long>("CNT_HEAT_TS_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNT_ID</code>
     */
    public static final Sequence<Long> CNT_ID = new SequenceImpl<Long>("CNT_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CNT_PHONE_ID</code>
     */
    public static final Sequence<Long> CNT_PHONE_ID = new SequenceImpl<Long>("CNT_PHONE_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CSD_MODEM_ID</code>
     */
    public static final Sequence<Long> CSD_MODEM_ID = new SequenceImpl<Long>("CSD_MODEM_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CSD_MODEM_TYPE_ID</code>
     */
    public static final Sequence<Long> CSD_MODEM_TYPE_ID = new SequenceImpl<Long>("CSD_MODEM_TYPE_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CSD_SESSION_ID</code>
     */
    public static final Sequence<Long> CSD_SESSION_ID = new SequenceImpl<Long>("CSD_SESSION_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>CT_ID</code>
     */
    public static final Sequence<Long> CT_ID = new SequenceImpl<Long>("CT_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>ECDL_ID</code>
     */
    public static final Sequence<Long> ECDL_ID = new SequenceImpl<Long>("ECDL_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>ECML_ID</code>
     */
    public static final Sequence<Long> ECML_ID = new SequenceImpl<Long>("ECML_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>ELEMENT_ID</code>
     */
    public static final Sequence<Long> ELEMENT_ID = new SequenceImpl<Long>("ELEMENT_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>ELEMENT_NOTIFICATION_ID</code>
     */
    public static final Sequence<Long> ELEMENT_NOTIFICATION_ID = new SequenceImpl<Long>("ELEMENT_NOTIFICATION_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>EXMDL_ID</code>
     */
    public static final Sequence<Long> EXMDL_ID = new SequenceImpl<Long>("EXMDL_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>FLT_ID</code>
     */
    public static final Sequence<Long> FLT_ID = new SequenceImpl<Long>("FLT_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GEN_USK_COOR_ID</code>
     */
    public static final Sequence<Long> GEN_USK_COOR_ID = new SequenceImpl<Long>("GEN_USK_COOR_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GPIN_ID</code>
     */
    public static final Sequence<Long> GPIN_ID = new SequenceImpl<Long>("GPIN_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GPLG_ID</code>
     */
    public static final Sequence<Long> GPLG_ID = new SequenceImpl<Long>("GPLG_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GPM_ID</code>
     */
    public static final Sequence<Long> GPM_ID = new SequenceImpl<Long>("GPM_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GPRST_ID</code>
     */
    public static final Sequence<Long> GPRST_ID = new SequenceImpl<Long>("GPRST_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRAPHICS_CACHE</code>
     */
    public static final Sequence<Long> GRAPHICS_CACHE = new SequenceImpl<Long>("GRAPHICS_CACHE", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRAPHICS_VERSION</code>
     */
    public static final Sequence<Long> GRAPHICS_VERSION = new SequenceImpl<Long>("GRAPHICS_VERSION", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRD</code>
     */
    public static final Sequence<Long> GRD = new SequenceImpl<Long>("GRD", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDAP_ID</code>
     */
    public static final Sequence<Long> GRDAP_ID = new SequenceImpl<Long>("GRDAP_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDC_ID</code>
     */
    public static final Sequence<Long> GRDC_ID = new SequenceImpl<Long>("GRDC_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDG_ID</code>
     */
    public static final Sequence<Long> GRDG_ID = new SequenceImpl<Long>("GRDG_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDINF_ID</code>
     */
    public static final Sequence<Long> GRDINF_ID = new SequenceImpl<Long>("GRDINF_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDK_ID</code>
     */
    public static final Sequence<Long> GRDK_ID = new SequenceImpl<Long>("GRDK_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDLC_ID</code>
     */
    public static final Sequence<Long> GRDLC_ID = new SequenceImpl<Long>("GRDLC_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDLG_ID</code>
     */
    public static final Sequence<Long> GRDLG_ID = new SequenceImpl<Long>("GRDLG_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDL_ID</code>
     */
    public static final Sequence<Long> GRDL_ID = new SequenceImpl<Long>("GRDL_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDM_ID</code>
     */
    public static final Sequence<Long> GRDM_ID = new SequenceImpl<Long>("GRDM_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDP_ID</code>
     */
    public static final Sequence<Long> GRDP_ID = new SequenceImpl<Long>("GRDP_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDR_ID</code>
     */
    public static final Sequence<Long> GRDR_ID = new SequenceImpl<Long>("GRDR_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDSMSST_ID</code>
     */
    public static final Sequence<Long> GRDSMSST_ID = new SequenceImpl<Long>("GRDSMSST_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDS_ID</code>
     */
    public static final Sequence<Long> GRDS_ID = new SequenceImpl<Long>("GRDS_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDZC_ID</code>
     */
    public static final Sequence<Long> GRDZC_ID = new SequenceImpl<Long>("GRDZC_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRDZ_ID</code>
     */
    public static final Sequence<Long> GRDZ_ID = new SequenceImpl<Long>("GRDZ_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRPH_ID</code>
     */
    public static final Sequence<Long> GRPH_ID = new SequenceImpl<Long>("GRPH_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>GRP_ID</code>
     */
    public static final Sequence<Long> GRP_ID = new SequenceImpl<Long>("GRP_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>HOME_ID</code>
     */
    public static final Sequence<Long> HOME_ID = new SequenceImpl<Long>("HOME_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>INTF_ID</code>
     */
    public static final Sequence<Long> INTF_ID = new SequenceImpl<Long>("INTF_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>LED_CONTROL_RECORD_ID</code>
     */
    public static final Sequence<Long> LED_CONTROL_RECORD_ID = new SequenceImpl<Long>("LED_CONTROL_RECORD_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>LIGHT_ACTION_ID</code>
     */
    public static final Sequence<Long> LIGHT_ACTION_ID = new SequenceImpl<Long>("LIGHT_ACTION_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>LIGHT_BOX_ID</code>
     */
    public static final Sequence<Long> LIGHT_BOX_ID = new SequenceImpl<Long>("LIGHT_BOX_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>LTBLK_ID</code>
     */
    public static final Sequence<Long> LTBLK_ID = new SequenceImpl<Long>("LTBLK_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>LTLINE_ID</code>
     */
    public static final Sequence<Long> LTLINE_ID = new SequenceImpl<Long>("LTLINE_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>LTSHD_ID</code>
     */
    public static final Sequence<Long> LTSHD_ID = new SequenceImpl<Long>("LTSHD_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>LTSHT_ID</code>
     */
    public static final Sequence<Long> LTSHT_ID = new SequenceImpl<Long>("LTSHT_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>MSA_ID</code>
     */
    public static final Sequence<Long> MSA_ID = new SequenceImpl<Long>("MSA_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>NORMATIVE_CNT_LINK_ID</code>
     */
    public static final Sequence<Long> NORMATIVE_CNT_LINK_ID = new SequenceImpl<Long>("NORMATIVE_CNT_LINK_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>NORMATIVE_ELCTR_ID</code>
     */
    public static final Sequence<Long> NORMATIVE_ELCTR_ID = new SequenceImpl<Long>("NORMATIVE_ELCTR_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>NORMATIVE_GAS_ID</code>
     */
    public static final Sequence<Long> NORMATIVE_GAS_ID = new SequenceImpl<Long>("NORMATIVE_GAS_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>NORMATIVE_HEAT_ID</code>
     */
    public static final Sequence<Long> NORMATIVE_HEAT_ID = new SequenceImpl<Long>("NORMATIVE_HEAT_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>NORMATIVE_ID</code>
     */
    public static final Sequence<Long> NORMATIVE_ID = new SequenceImpl<Long>("NORMATIVE_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>NORMATIVE_WATER_ID</code>
     */
    public static final Sequence<Long> NORMATIVE_WATER_ID = new SequenceImpl<Long>("NORMATIVE_WATER_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>OBJ_CONTROL_LOG_ID</code>
     */
    public static final Sequence<Long> OBJ_CONTROL_LOG_ID = new SequenceImpl<Long>("OBJ_CONTROL_LOG_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PCS_ID</code>
     */
    public static final Sequence<Long> PCS_ID = new SequenceImpl<Long>("PCS_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PKELOG_ID</code>
     */
    public static final Sequence<Long> PKELOG_ID = new SequenceImpl<Long>("PKELOG_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PRS_ID</code>
     */
    public static final Sequence<Long> PRS_ID = new SequenceImpl<Long>("PRS_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PZN_ID</code>
     */
    public static final Sequence<Long> PZN_ID = new SequenceImpl<Long>("PZN_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RDB$BACKUP_HISTORY</code>
     */
    public static final Sequence<Long> RDB$BACKUP_HISTORY = new SequenceImpl<Long>("RDB$BACKUP_HISTORY", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RDB$CONSTRAINT_NAME</code>
     */
    public static final Sequence<Long> RDB$CONSTRAINT_NAME = new SequenceImpl<Long>("RDB$CONSTRAINT_NAME", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RDB$EXCEPTIONS</code>
     */
    public static final Sequence<Long> RDB$EXCEPTIONS = new SequenceImpl<Long>("RDB$EXCEPTIONS", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RDB$FIELD_NAME</code>
     */
    public static final Sequence<Long> RDB$FIELD_NAME = new SequenceImpl<Long>("RDB$FIELD_NAME", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RDB$INDEX_NAME</code>
     */
    public static final Sequence<Long> RDB$INDEX_NAME = new SequenceImpl<Long>("RDB$INDEX_NAME", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RDB$PROCEDURES</code>
     */
    public static final Sequence<Long> RDB$PROCEDURES = new SequenceImpl<Long>("RDB$PROCEDURES", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RDB$SECURITY_CLASS</code>
     */
    public static final Sequence<Long> RDB$SECURITY_CLASS = new SequenceImpl<Long>("RDB$SECURITY_CLASS", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RDB$TRIGGER_NAME</code>
     */
    public static final Sequence<Long> RDB$TRIGGER_NAME = new SequenceImpl<Long>("RDB$TRIGGER_NAME", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>REPORT_DATA_ID</code>
     */
    public static final Sequence<Long> REPORT_DATA_ID = new SequenceImpl<Long>("REPORT_DATA_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>REPORT_DATA_VERSION</code>
     */
    public static final Sequence<Long> REPORT_DATA_VERSION = new SequenceImpl<Long>("REPORT_DATA_VERSION", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>REPORT_STRUCT_ID</code>
     */
    public static final Sequence<Long> REPORT_STRUCT_ID = new SequenceImpl<Long>("REPORT_STRUCT_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>REPORT_STRUCT_VERSION</code>
     */
    public static final Sequence<Long> REPORT_STRUCT_VERSION = new SequenceImpl<Long>("REPORT_STRUCT_VERSION", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RGN_ID</code>
     */
    public static final Sequence<Long> RGN_ID = new SequenceImpl<Long>("RGN_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RPTV_ID</code>
     */
    public static final Sequence<Long> RPTV_ID = new SequenceImpl<Long>("RPTV_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RPT_ID</code>
     */
    public static final Sequence<Long> RPT_ID = new SequenceImpl<Long>("RPT_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>RULE_ID</code>
     */
    public static final Sequence<Long> RULE_ID = new SequenceImpl<Long>("RULE_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>SQL$DEFAULT</code>
     */
    public static final Sequence<Long> SQL$DEFAULT = new SequenceImpl<Long>("SQL$DEFAULT", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>STRT_ID</code>
     */
    public static final Sequence<Long> STRT_ID = new SequenceImpl<Long>("STRT_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>TRSL_ID</code>
     */
    public static final Sequence<Long> TRSL_ID = new SequenceImpl<Long>("TRSL_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>USER_ID</code>
     */
    public static final Sequence<Long> USER_ID = new SequenceImpl<Long>("USER_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>USKC_ID</code>
     */
    public static final Sequence<Long> USKC_ID = new SequenceImpl<Long>("USKC_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>USKEC_ID</code>
     */
    public static final Sequence<Long> USKEC_ID = new SequenceImpl<Long>("USKEC_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>USKLL_ID</code>
     */
    public static final Sequence<Long> USKLL_ID = new SequenceImpl<Long>("USKLL_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>USK_CURR_ID</code>
     */
    public static final Sequence<Long> USK_CURR_ID = new SequenceImpl<Long>("USK_CURR_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>USK_EXT_MODULE_ID</code>
     */
    public static final Sequence<Long> USK_EXT_MODULE_ID = new SequenceImpl<Long>("USK_EXT_MODULE_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>USK_ID</code>
     */
    public static final Sequence<Long> USK_ID = new SequenceImpl<Long>("USK_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>USK_JOURNAL_ID</code>
     */
    public static final Sequence<Long> USK_JOURNAL_ID = new SequenceImpl<Long>("USK_JOURNAL_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>USK_LOG_ID</code>
     */
    public static final Sequence<Long> USK_LOG_ID = new SequenceImpl<Long>("USK_LOG_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>VALVE_ID</code>
     */
    public static final Sequence<Long> VALVE_ID = new SequenceImpl<Long>("VALVE_ID", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.BIGINT);
}
