/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.Keys;
import ru.smartsarov.citylighting.sprut.tables.records.ChangesGuardLineRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChangesGuardLine extends TableImpl<ChangesGuardLineRecord> {

    private static final long serialVersionUID = -1711064335;

    /**
     * The reference instance of <code>CHANGES_GUARD_LINE</code>
     */
    public static final ChangesGuardLine CHANGES_GUARD_LINE = new ChangesGuardLine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChangesGuardLineRecord> getRecordType() {
        return ChangesGuardLineRecord.class;
    }

    /**
     * The column <code>CHANGES_GUARD_LINE.ID</code>.
     */
    public final TableField<ChangesGuardLineRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.LOGIN</code>.
     */
    public final TableField<ChangesGuardLineRecord, String> LOGIN = createField("LOGIN", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.CHANGE_TIME</code>.
     */
    public final TableField<ChangesGuardLineRecord, Timestamp> CHANGE_TIME = createField("CHANGE_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.CHANGE_TYPE</code>.
     */
    public final TableField<ChangesGuardLineRecord, Integer> CHANGE_TYPE = createField("CHANGE_TYPE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.GRDL_ID</code>.
     */
    public final TableField<ChangesGuardLineRecord, Integer> GRDL_ID = createField("GRDL_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.GRDL_ZID</code>.
     */
    public final TableField<ChangesGuardLineRecord, Integer> GRDL_ZID = createField("GRDL_ZID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.GRDL_NAME</code>.
     */
    public final TableField<ChangesGuardLineRecord, String> GRDL_NAME = createField("GRDL_NAME", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.GRDL_TYPE</code>.
     */
    public final TableField<ChangesGuardLineRecord, Integer> GRDL_TYPE = createField("GRDL_TYPE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.GRDL_UNK_ID</code>.
     */
    public final TableField<ChangesGuardLineRecord, Integer> GRDL_UNK_ID = createField("GRDL_UNK_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.GRDL_NUM</code>.
     */
    public final TableField<ChangesGuardLineRecord, Integer> GRDL_NUM = createField("GRDL_NUM", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.GRDL_ON</code>.
     */
    public final TableField<ChangesGuardLineRecord, Integer> GRDL_ON = createField("GRDL_ON", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.GRDL_PRIORITY</code>.
     */
    public final TableField<ChangesGuardLineRecord, Integer> GRDL_PRIORITY = createField("GRDL_PRIORITY", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.GRDL_DELAY</code>.
     */
    public final TableField<ChangesGuardLineRecord, Integer> GRDL_DELAY = createField("GRDL_DELAY", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.GRDL_REM</code>.
     */
    public final TableField<ChangesGuardLineRecord, String> GRDL_REM = createField("GRDL_REM", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>CHANGES_GUARD_LINE.GRDL_EXMODULE</code>.
     */
    public final TableField<ChangesGuardLineRecord, Integer> GRDL_EXMODULE = createField("GRDL_EXMODULE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>CHANGES_GUARD_LINE</code> table reference
     */
    public ChangesGuardLine() {
        this(DSL.name("CHANGES_GUARD_LINE"), null);
    }

    /**
     * Create an aliased <code>CHANGES_GUARD_LINE</code> table reference
     */
    public ChangesGuardLine(String alias) {
        this(DSL.name(alias), CHANGES_GUARD_LINE);
    }

    /**
     * Create an aliased <code>CHANGES_GUARD_LINE</code> table reference
     */
    public ChangesGuardLine(Name alias) {
        this(alias, CHANGES_GUARD_LINE);
    }

    private ChangesGuardLine(Name alias, Table<ChangesGuardLineRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChangesGuardLine(Name alias, Table<ChangesGuardLineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ChangesGuardLine(Table<O> child, ForeignKey<O, ChangesGuardLineRecord> key) {
        super(child, key, CHANGES_GUARD_LINE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ChangesGuardLineRecord> getPrimaryKey() {
        return Keys.CHANGES_GUARD_LINE_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ChangesGuardLineRecord>> getKeys() {
        return Arrays.<UniqueKey<ChangesGuardLineRecord>>asList(Keys.CHANGES_GUARD_LINE_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChangesGuardLine as(String alias) {
        return new ChangesGuardLine(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChangesGuardLine as(Name alias) {
        return new ChangesGuardLine(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChangesGuardLine rename(String name) {
        return new ChangesGuardLine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChangesGuardLine rename(Name name) {
        return new ChangesGuardLine(name, null);
    }
}
