/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.Keys;
import ru.smartsarov.citylighting.sprut.tables.records.CntGroupDependRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CntGroupDepend extends TableImpl<CntGroupDependRecord> {

    private static final long serialVersionUID = 172673508;

    /**
     * The reference instance of <code>CNT_GROUP_DEPEND</code>
     */
    public static final CntGroupDepend CNT_GROUP_DEPEND = new CntGroupDepend();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CntGroupDependRecord> getRecordType() {
        return CntGroupDependRecord.class;
    }

    /**
     * The column <code>CNT_GROUP_DEPEND.GROUP_ID</code>.
     */
    public final TableField<CntGroupDependRecord, Integer> GROUP_ID = createField("GROUP_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CNT_GROUP_DEPEND.ELEMENT_ID</code>.
     */
    public final TableField<CntGroupDependRecord, Integer> ELEMENT_ID = createField("ELEMENT_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CNT_GROUP_DEPEND.ELEMENT_TYPE</code>.
     */
    public final TableField<CntGroupDependRecord, Integer> ELEMENT_TYPE = createField("ELEMENT_TYPE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CNT_GROUP_DEPEND.BALANCE_TYPE</code>.
     */
    public final TableField<CntGroupDependRecord, Integer> BALANCE_TYPE = createField("BALANCE_TYPE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>CNT_GROUP_DEPEND</code> table reference
     */
    public CntGroupDepend() {
        this(DSL.name("CNT_GROUP_DEPEND"), null);
    }

    /**
     * Create an aliased <code>CNT_GROUP_DEPEND</code> table reference
     */
    public CntGroupDepend(String alias) {
        this(DSL.name(alias), CNT_GROUP_DEPEND);
    }

    /**
     * Create an aliased <code>CNT_GROUP_DEPEND</code> table reference
     */
    public CntGroupDepend(Name alias) {
        this(alias, CNT_GROUP_DEPEND);
    }

    private CntGroupDepend(Name alias, Table<CntGroupDependRecord> aliased) {
        this(alias, aliased, null);
    }

    private CntGroupDepend(Name alias, Table<CntGroupDependRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CntGroupDepend(Table<O> child, ForeignKey<O, CntGroupDependRecord> key) {
        super(child, key, CNT_GROUP_DEPEND);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CntGroupDependRecord> getPrimaryKey() {
        return Keys.INTEG_183;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CntGroupDependRecord>> getKeys() {
        return Arrays.<UniqueKey<CntGroupDependRecord>>asList(Keys.INTEG_183);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntGroupDepend as(String alias) {
        return new CntGroupDepend(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CntGroupDepend as(Name alias) {
        return new CntGroupDepend(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CntGroupDepend rename(String name) {
        return new CntGroupDepend(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CntGroupDepend rename(Name name) {
        return new CntGroupDepend(name, null);
    }
}
