/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.Keys;
import ru.smartsarov.citylighting.sprut.tables.records.CntvRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cntv extends TableImpl<CntvRecord> {

    private static final long serialVersionUID = -2010020594;

    /**
     * The reference instance of <code>CNTV</code>
     */
    public static final Cntv CNTV = new Cntv();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CntvRecord> getRecordType() {
        return CntvRecord.class;
    }

    /**
     * The column <code>CNTV.CNTV_ID</code>.
     */
    public final TableField<CntvRecord, Integer> CNTV_ID = createField("CNTV_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>CNTV.CNTV_VALUE1</code>.
     */
    public final TableField<CntvRecord, Double> CNTV_VALUE1 = createField("CNTV_VALUE1", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>CNTV.CNTV_VALUE2</code>.
     */
    public final TableField<CntvRecord, Double> CNTV_VALUE2 = createField("CNTV_VALUE2", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>CNTV.CNTV_VALUE3</code>.
     */
    public final TableField<CntvRecord, Double> CNTV_VALUE3 = createField("CNTV_VALUE3", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>CNTV.CNTV_VALUE4</code>.
     */
    public final TableField<CntvRecord, Double> CNTV_VALUE4 = createField("CNTV_VALUE4", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>CNTV.CNTV_VALUE5</code>.
     */
    public final TableField<CntvRecord, Double> CNTV_VALUE5 = createField("CNTV_VALUE5", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>CNTV.CNTV_DATE</code>.
     */
    public final TableField<CntvRecord, Timestamp> CNTV_DATE = createField("CNTV_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>CNTV.CNTV_STATE</code>.
     */
    public final TableField<CntvRecord, Integer> CNTV_STATE = createField("CNTV_STATE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>CNTV.CNTV_VALUE6</code>.
     */
    public final TableField<CntvRecord, Double> CNTV_VALUE6 = createField("CNTV_VALUE6", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>CNTV.CNTV_VALUE7</code>.
     */
    public final TableField<CntvRecord, Double> CNTV_VALUE7 = createField("CNTV_VALUE7", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>CNTV.CNTV_VALUE8</code>.
     */
    public final TableField<CntvRecord, Double> CNTV_VALUE8 = createField("CNTV_VALUE8", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>CNTV.CNTV_VALUE9</code>.
     */
    public final TableField<CntvRecord, Double> CNTV_VALUE9 = createField("CNTV_VALUE9", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>CNTV.CNTV_VALUE10</code>.
     */
    public final TableField<CntvRecord, Double> CNTV_VALUE10 = createField("CNTV_VALUE10", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>CNTV</code> table reference
     */
    public Cntv() {
        this(DSL.name("CNTV"), null);
    }

    /**
     * Create an aliased <code>CNTV</code> table reference
     */
    public Cntv(String alias) {
        this(DSL.name(alias), CNTV);
    }

    /**
     * Create an aliased <code>CNTV</code> table reference
     */
    public Cntv(Name alias) {
        this(alias, CNTV);
    }

    private Cntv(Name alias, Table<CntvRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cntv(Name alias, Table<CntvRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Cntv(Table<O> child, ForeignKey<O, CntvRecord> key) {
        super(child, key, CNTV);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CntvRecord> getPrimaryKey() {
        return Keys.INTEG_26;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CntvRecord>> getKeys() {
        return Arrays.<UniqueKey<CntvRecord>>asList(Keys.INTEG_26);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cntv as(String alias) {
        return new Cntv(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cntv as(Name alias) {
        return new Cntv(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cntv rename(String name) {
        return new Cntv(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cntv rename(Name name) {
        return new Cntv(name, null);
    }
}
