/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.tables.records.GetCntc_218Record;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetCntc_218 extends TableImpl<GetCntc_218Record> {

    private static final long serialVersionUID = -105709265;

    /**
     * The reference instance of <code>GET_CNTC_218</code>
     */
    public static final GetCntc_218 GET_CNTC_218 = new GetCntc_218();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetCntc_218Record> getRecordType() {
        return GetCntc_218Record.class;
    }

    /**
     * The column <code>GET_CNTC_218.CNT_ID</code>.
     */
    public final TableField<GetCntc_218Record, Integer> CNT_ID = createField("CNT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_CNTC_218.CNT_AB_ID</code>.
     */
    public final TableField<GetCntc_218Record, Integer> CNT_AB_ID = createField("CNT_AB_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_CNTC_218.CNT_SNUM</code>.
     */
    public final TableField<GetCntc_218Record, String> CNT_SNUM = createField("CNT_SNUM", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>GET_CNTC_218.CNT_NAME</code>.
     */
    public final TableField<GetCntc_218Record, String> CNT_NAME = createField("CNT_NAME", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>GET_CNTC_218.CNTB_NAME</code>.
     */
    public final TableField<GetCntc_218Record, String> CNTB_NAME = createField("CNTB_NAME", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>GET_CNTC_218.USK_IP</code>.
     */
    public final TableField<GetCntc_218Record, String> USK_IP = createField("USK_IP", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>GET_CNTC_218.Q</code>.
     */
    public final TableField<GetCntc_218Record, Double> Q = createField("Q", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.W</code>.
     */
    public final TableField<GetCntc_218Record, Double> W = createField("W", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.G1</code>.
     */
    public final TableField<GetCntc_218Record, Double> G1 = createField("G1", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.G2</code>.
     */
    public final TableField<GetCntc_218Record, Double> G2 = createField("G2", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.M1</code>.
     */
    public final TableField<GetCntc_218Record, Double> M1 = createField("M1", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.M2</code>.
     */
    public final TableField<GetCntc_218Record, Double> M2 = createField("M2", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.TA</code>.
     */
    public final TableField<GetCntc_218Record, Double> TA = createField("TA", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.T1</code>.
     */
    public final TableField<GetCntc_218Record, Double> T1 = createField("T1", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.T2</code>.
     */
    public final TableField<GetCntc_218Record, Double> T2 = createField("T2", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.T3</code>.
     */
    public final TableField<GetCntc_218Record, Double> T3 = createField("T3", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.T4</code>.
     */
    public final TableField<GetCntc_218Record, Double> T4 = createField("T4", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.P1</code>.
     */
    public final TableField<GetCntc_218Record, Double> P1 = createField("P1", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.P2</code>.
     */
    public final TableField<GetCntc_218Record, Double> P2 = createField("P2", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.P3</code>.
     */
    public final TableField<GetCntc_218Record, Double> P3 = createField("P3", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_CNTC_218.CTIME</code>.
     */
    public final TableField<GetCntc_218Record, Timestamp> CTIME = createField("CTIME", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>GET_CNTC_218.STATE</code>.
     */
    public final TableField<GetCntc_218Record, Integer> STATE = createField("STATE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_CNTC_218.ADR_ID</code>.
     */
    public final TableField<GetCntc_218Record, Integer> ADR_ID = createField("ADR_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_CNTC_218.FLT_ID</code>.
     */
    public final TableField<GetCntc_218Record, Integer> FLT_ID = createField("FLT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_CNTC_218.HOME_ID</code>.
     */
    public final TableField<GetCntc_218Record, Integer> HOME_ID = createField("HOME_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_CNTC_218.STRT_ID</code>.
     */
    public final TableField<GetCntc_218Record, Integer> STRT_ID = createField("STRT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_CNTC_218.CITY_ID</code>.
     */
    public final TableField<GetCntc_218Record, Integer> CITY_ID = createField("CITY_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>GET_CNTC_218</code> table reference
     */
    public GetCntc_218() {
        this(DSL.name("GET_CNTC_218"), null);
    }

    /**
     * Create an aliased <code>GET_CNTC_218</code> table reference
     */
    public GetCntc_218(String alias) {
        this(DSL.name(alias), GET_CNTC_218);
    }

    /**
     * Create an aliased <code>GET_CNTC_218</code> table reference
     */
    public GetCntc_218(Name alias) {
        this(alias, GET_CNTC_218);
    }

    private GetCntc_218(Name alias, Table<GetCntc_218Record> aliased) {
        this(alias, aliased, new Field[0]);
    }

    private GetCntc_218(Name alias, Table<GetCntc_218Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GetCntc_218(Table<O> child, ForeignKey<O, GetCntc_218Record> key) {
        super(child, key, GET_CNTC_218);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetCntc_218 as(String alias) {
        return new GetCntc_218(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetCntc_218 as(Name alias) {
        return new GetCntc_218(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetCntc_218 rename(String name) {
        return new GetCntc_218(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetCntc_218 rename(Name name) {
        return new GetCntc_218(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetCntc_218 call() {
        return new GetCntc_218(DSL.name(getName()), null, new Field[] { 
        });
    }
}
