/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.tables.records.GetCntControlRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetCntControl extends TableImpl<GetCntControlRecord> {

    private static final long serialVersionUID = -1832732597;

    /**
     * The reference instance of <code>GET_CNT_CONTROL</code>
     */
    public static final GetCntControl GET_CNT_CONTROL = new GetCntControl();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetCntControlRecord> getRecordType() {
        return GetCntControlRecord.class;
    }

    /**
     * The column <code>GET_CNT_CONTROL.CNT_ID</code>.
     */
    public final TableField<GetCntControlRecord, Integer> CNT_ID = createField("CNT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_CNT_CONTROL.CNTCTRL_ACTION</code>.
     */
    public final TableField<GetCntControlRecord, Integer> CNTCTRL_ACTION = createField("CNTCTRL_ACTION", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_CNT_CONTROL.CNTCTRL_LIMIT</code>.
     */
    public final TableField<GetCntControlRecord, Integer> CNTCTRL_LIMIT = createField("CNTCTRL_LIMIT", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_CNT_CONTROL.CNTCTRL_SYNC</code>.
     */
    public final TableField<GetCntControlRecord, Integer> CNTCTRL_SYNC = createField("CNTCTRL_SYNC", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>GET_CNT_CONTROL</code> table reference
     */
    public GetCntControl() {
        this(DSL.name("GET_CNT_CONTROL"), null);
    }

    /**
     * Create an aliased <code>GET_CNT_CONTROL</code> table reference
     */
    public GetCntControl(String alias) {
        this(DSL.name(alias), GET_CNT_CONTROL);
    }

    /**
     * Create an aliased <code>GET_CNT_CONTROL</code> table reference
     */
    public GetCntControl(Name alias) {
        this(alias, GET_CNT_CONTROL);
    }

    private GetCntControl(Name alias, Table<GetCntControlRecord> aliased) {
        this(alias, aliased, new Field[3]);
    }

    private GetCntControl(Name alias, Table<GetCntControlRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GetCntControl(Table<O> child, ForeignKey<O, GetCntControlRecord> key) {
        super(child, key, GET_CNT_CONTROL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetCntControl as(String alias) {
        return new GetCntControl(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetCntControl as(Name alias) {
        return new GetCntControl(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetCntControl rename(String name) {
        return new GetCntControl(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetCntControl rename(Name name) {
        return new GetCntControl(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetCntControl call(Integer cntid, String login, String pass) {
        return new GetCntControl(DSL.name(getName()), null, new Field[] { 
              DSL.val(cntid, org.jooq.impl.SQLDataType.INTEGER)
            , DSL.val(login, org.jooq.impl.SQLDataType.VARCHAR(32))
            , DSL.val(pass, org.jooq.impl.SQLDataType.VARCHAR(32))
        });
    }

    /**
     * Call this table-valued function
     */
    public GetCntControl call(Field<Integer> cntid, Field<String> login, Field<String> pass) {
        return new GetCntControl(DSL.name(getName()), null, new Field[] { 
              cntid
            , login
            , pass
        });
    }
}
