/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.tables.records.GetGuardPinLogSelect_1Record;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetGuardPinLogSelect_1 extends TableImpl<GetGuardPinLogSelect_1Record> {

    private static final long serialVersionUID = 462141787;

    /**
     * The reference instance of <code>GET_GUARD_PIN_LOG_SELECT_1</code>
     */
    public static final GetGuardPinLogSelect_1 GET_GUARD_PIN_LOG_SELECT_1 = new GetGuardPinLogSelect_1();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetGuardPinLogSelect_1Record> getRecordType() {
        return GetGuardPinLogSelect_1Record.class;
    }

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GUARD_PIN_ID</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GUARD_PIN_ID = createField("GUARD_PIN_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GUARD_PIN_NAME</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, String> GUARD_PIN_NAME = createField("GUARD_PIN_NAME", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPLG_ID</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPLG_ID = createField("GPLG_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPLG_TYPE</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPLG_TYPE = createField("GPLG_TYPE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPLG_AVALUE</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Double> GPLG_AVALUE = createField("GPLG_AVALUE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPLG_DVALUE</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPLG_DVALUE = createField("GPLG_DVALUE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPLG_STATE</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPLG_STATE = createField("GPLG_STATE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPLG_LDATE</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Timestamp> GPLG_LDATE = createField("GPLG_LDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPLG_SDATE</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Timestamp> GPLG_SDATE = createField("GPLG_SDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPLG_USK_ID</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPLG_USK_ID = createField("GPLG_USK_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPLG_EVENT</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPLG_EVENT = createField("GPLG_EVENT", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPLG_ACTION</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPLG_ACTION = createField("GPLG_ACTION", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPIN_ZID</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPIN_ZID = createField("GPIN_ZID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPIN_TYPE</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPIN_TYPE = createField("GPIN_TYPE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPIN_DEVTYPE</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPIN_DEVTYPE = createField("GPIN_DEVTYPE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPIN_ENTRY</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPIN_ENTRY = createField("GPIN_ENTRY", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPIN_NETADR</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPIN_NETADR = createField("GPIN_NETADR", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPIN_NAME</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, String> GPIN_NAME = createField("GPIN_NAME", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPIN_DELAY</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPIN_DELAY = createField("GPIN_DELAY", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPIN_ATYPE</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPIN_ATYPE = createField("GPIN_ATYPE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPIN_ON</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, Integer> GPIN_ON = createField("GPIN_ON", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.GPIN_REM</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, String> GPIN_REM = createField("GPIN_REM", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.NAME</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_SELECT_1.STATE</code>.
     */
    public final TableField<GetGuardPinLogSelect_1Record, String> STATE = createField("STATE", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>GET_GUARD_PIN_LOG_SELECT_1</code> table reference
     */
    public GetGuardPinLogSelect_1() {
        this(DSL.name("GET_GUARD_PIN_LOG_SELECT_1"), null);
    }

    /**
     * Create an aliased <code>GET_GUARD_PIN_LOG_SELECT_1</code> table reference
     */
    public GetGuardPinLogSelect_1(String alias) {
        this(DSL.name(alias), GET_GUARD_PIN_LOG_SELECT_1);
    }

    /**
     * Create an aliased <code>GET_GUARD_PIN_LOG_SELECT_1</code> table reference
     */
    public GetGuardPinLogSelect_1(Name alias) {
        this(alias, GET_GUARD_PIN_LOG_SELECT_1);
    }

    private GetGuardPinLogSelect_1(Name alias, Table<GetGuardPinLogSelect_1Record> aliased) {
        this(alias, aliased, new Field[5]);
    }

    private GetGuardPinLogSelect_1(Name alias, Table<GetGuardPinLogSelect_1Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GetGuardPinLogSelect_1(Table<O> child, ForeignKey<O, GetGuardPinLogSelect_1Record> key) {
        super(child, key, GET_GUARD_PIN_LOG_SELECT_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetGuardPinLogSelect_1 as(String alias) {
        return new GetGuardPinLogSelect_1(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetGuardPinLogSelect_1 as(Name alias) {
        return new GetGuardPinLogSelect_1(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetGuardPinLogSelect_1 rename(String name) {
        return new GetGuardPinLogSelect_1(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetGuardPinLogSelect_1 rename(Name name) {
        return new GetGuardPinLogSelect_1(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetGuardPinLogSelect_1 call(String login, String pass, Integer uskId, Timestamp datetimeStart, Timestamp datetimeEnd) {
        return new GetGuardPinLogSelect_1(DSL.name(getName()), null, new Field[] { 
              DSL.val(login, org.jooq.impl.SQLDataType.VARCHAR(32))
            , DSL.val(pass, org.jooq.impl.SQLDataType.VARCHAR(32))
            , DSL.val(uskId, org.jooq.impl.SQLDataType.INTEGER)
            , DSL.val(datetimeStart, org.jooq.impl.SQLDataType.TIMESTAMP)
            , DSL.val(datetimeEnd, org.jooq.impl.SQLDataType.TIMESTAMP)
        });
    }

    /**
     * Call this table-valued function
     */
    public GetGuardPinLogSelect_1 call(Field<String> login, Field<String> pass, Field<Integer> uskId, Field<Timestamp> datetimeStart, Field<Timestamp> datetimeEnd) {
        return new GetGuardPinLogSelect_1(DSL.name(getName()), null, new Field[] { 
              login
            , pass
            , uskId
            , datetimeStart
            , datetimeEnd
        });
    }
}
