/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.tables.records.GetGuardPinLogLastEventRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetGuardPinLogLastEvent extends TableImpl<GetGuardPinLogLastEventRecord> {

    private static final long serialVersionUID = 78454482;

    /**
     * The reference instance of <code>GET_GUARD_PIN_LOG_LAST_EVENT</code>
     */
    public static final GetGuardPinLogLastEvent GET_GUARD_PIN_LOG_LAST_EVENT = new GetGuardPinLogLastEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetGuardPinLogLastEventRecord> getRecordType() {
        return GetGuardPinLogLastEventRecord.class;
    }

    /**
     * The column <code>GET_GUARD_PIN_LOG_LAST_EVENT.USK_ID</code>.
     */
    public final TableField<GetGuardPinLogLastEventRecord, Integer> USK_ID = createField("USK_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_LAST_EVENT.GPLG_EVENT</code>.
     */
    public final TableField<GetGuardPinLogLastEventRecord, Integer> GPLG_EVENT = createField("GPLG_EVENT", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_LAST_EVENT.GPLG_ACTION</code>.
     */
    public final TableField<GetGuardPinLogLastEventRecord, Integer> GPLG_ACTION = createField("GPLG_ACTION", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_LAST_EVENT.GPLG_LDATE</code>.
     */
    public final TableField<GetGuardPinLogLastEventRecord, Timestamp> GPLG_LDATE = createField("GPLG_LDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_LAST_EVENT.GPLG_SDATE</code>.
     */
    public final TableField<GetGuardPinLogLastEventRecord, Timestamp> GPLG_SDATE = createField("GPLG_SDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_LAST_EVENT.DEBUG_INFO</code>.
     */
    public final TableField<GetGuardPinLogLastEventRecord, Integer> DEBUG_INFO = createField("DEBUG_INFO", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GUARD_PIN_LOG_LAST_EVENT.DEBUG_TIME</code>.
     */
    public final TableField<GetGuardPinLogLastEventRecord, Timestamp> DEBUG_TIME = createField("DEBUG_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>GET_GUARD_PIN_LOG_LAST_EVENT</code> table reference
     */
    public GetGuardPinLogLastEvent() {
        this(DSL.name("GET_GUARD_PIN_LOG_LAST_EVENT"), null);
    }

    /**
     * Create an aliased <code>GET_GUARD_PIN_LOG_LAST_EVENT</code> table reference
     */
    public GetGuardPinLogLastEvent(String alias) {
        this(DSL.name(alias), GET_GUARD_PIN_LOG_LAST_EVENT);
    }

    /**
     * Create an aliased <code>GET_GUARD_PIN_LOG_LAST_EVENT</code> table reference
     */
    public GetGuardPinLogLastEvent(Name alias) {
        this(alias, GET_GUARD_PIN_LOG_LAST_EVENT);
    }

    private GetGuardPinLogLastEvent(Name alias, Table<GetGuardPinLogLastEventRecord> aliased) {
        this(alias, aliased, new Field[3]);
    }

    private GetGuardPinLogLastEvent(Name alias, Table<GetGuardPinLogLastEventRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GetGuardPinLogLastEvent(Table<O> child, ForeignKey<O, GetGuardPinLogLastEventRecord> key) {
        super(child, key, GET_GUARD_PIN_LOG_LAST_EVENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetGuardPinLogLastEvent as(String alias) {
        return new GetGuardPinLogLastEvent(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetGuardPinLogLastEvent as(Name alias) {
        return new GetGuardPinLogLastEvent(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetGuardPinLogLastEvent rename(String name) {
        return new GetGuardPinLogLastEvent(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetGuardPinLogLastEvent rename(Name name) {
        return new GetGuardPinLogLastEvent(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetGuardPinLogLastEvent call(String login, String pass, Integer guskAction) {
        return new GetGuardPinLogLastEvent(DSL.name(getName()), null, new Field[] { 
              DSL.val(login, org.jooq.impl.SQLDataType.VARCHAR(32))
            , DSL.val(pass, org.jooq.impl.SQLDataType.VARCHAR(32))
            , DSL.val(guskAction, org.jooq.impl.SQLDataType.INTEGER)
        });
    }

    /**
     * Call this table-valued function
     */
    public GetGuardPinLogLastEvent call(Field<String> login, Field<String> pass, Field<Integer> guskAction) {
        return new GetGuardPinLogLastEvent(DSL.name(getName()), null, new Field[] { 
              login
            , pass
            , guskAction
        });
    }
}
