/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.tables.records.GetGrpTypeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetGrpType extends TableImpl<GetGrpTypeRecord> {

    private static final long serialVersionUID = 1879166394;

    /**
     * The reference instance of <code>GET_GRP_TYPE</code>
     */
    public static final GetGrpType GET_GRP_TYPE = new GetGrpType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetGrpTypeRecord> getRecordType() {
        return GetGrpTypeRecord.class;
    }

    /**
     * The column <code>GET_GRP_TYPE.GRPT_ID</code>.
     */
    public final TableField<GetGrpTypeRecord, Integer> GRPT_ID = createField("GRPT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_GRP_TYPE.GRPT_NAME</code>.
     */
    public final TableField<GetGrpTypeRecord, String> GRPT_NAME = createField("GRPT_NAME", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>GET_GRP_TYPE.GRPT_REM</code>.
     */
    public final TableField<GetGrpTypeRecord, String> GRPT_REM = createField("GRPT_REM", org.jooq.impl.SQLDataType.VARCHAR(60), this, "");

    /**
     * Create a <code>GET_GRP_TYPE</code> table reference
     */
    public GetGrpType() {
        this(DSL.name("GET_GRP_TYPE"), null);
    }

    /**
     * Create an aliased <code>GET_GRP_TYPE</code> table reference
     */
    public GetGrpType(String alias) {
        this(DSL.name(alias), GET_GRP_TYPE);
    }

    /**
     * Create an aliased <code>GET_GRP_TYPE</code> table reference
     */
    public GetGrpType(Name alias) {
        this(alias, GET_GRP_TYPE);
    }

    private GetGrpType(Name alias, Table<GetGrpTypeRecord> aliased) {
        this(alias, aliased, new Field[0]);
    }

    private GetGrpType(Name alias, Table<GetGrpTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GetGrpType(Table<O> child, ForeignKey<O, GetGrpTypeRecord> key) {
        super(child, key, GET_GRP_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetGrpType as(String alias) {
        return new GetGrpType(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetGrpType as(Name alias) {
        return new GetGrpType(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetGrpType rename(String name) {
        return new GetGrpType(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetGrpType rename(Name name) {
        return new GetGrpType(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetGrpType call() {
        return new GetGrpType(DSL.name(getName()), null, new Field[] { 
        });
    }
}
