/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.tables.records.GetImpulseCntvRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetImpulseCntv extends TableImpl<GetImpulseCntvRecord> {

    private static final long serialVersionUID = 1929694847;

    /**
     * The reference instance of <code>GET_IMPULSE_CNTV</code>
     */
    public static final GetImpulseCntv GET_IMPULSE_CNTV = new GetImpulseCntv();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetImpulseCntvRecord> getRecordType() {
        return GetImpulseCntvRecord.class;
    }

    /**
     * The column <code>GET_IMPULSE_CNTV.ID</code>.
     */
    public final TableField<GetImpulseCntvRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.VALUE1</code>.
     */
    public final TableField<GetImpulseCntvRecord, Double> VALUE1 = createField("VALUE1", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.VALUE2</code>.
     */
    public final TableField<GetImpulseCntvRecord, Double> VALUE2 = createField("VALUE2", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.VALUE3</code>.
     */
    public final TableField<GetImpulseCntvRecord, Double> VALUE3 = createField("VALUE3", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.VALUE4</code>.
     */
    public final TableField<GetImpulseCntvRecord, Double> VALUE4 = createField("VALUE4", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.VALUE5</code>.
     */
    public final TableField<GetImpulseCntvRecord, Double> VALUE5 = createField("VALUE5", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.CDATE</code>.
     */
    public final TableField<GetImpulseCntvRecord, Timestamp> CDATE = createField("CDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.STATE</code>.
     */
    public final TableField<GetImpulseCntvRecord, Integer> STATE = createField("STATE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.VALUE6</code>.
     */
    public final TableField<GetImpulseCntvRecord, Double> VALUE6 = createField("VALUE6", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.VALUE7</code>.
     */
    public final TableField<GetImpulseCntvRecord, Double> VALUE7 = createField("VALUE7", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.VALUE8</code>.
     */
    public final TableField<GetImpulseCntvRecord, Double> VALUE8 = createField("VALUE8", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.VALUE9</code>.
     */
    public final TableField<GetImpulseCntvRecord, Double> VALUE9 = createField("VALUE9", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV.VALUE10</code>.
     */
    public final TableField<GetImpulseCntvRecord, Double> VALUE10 = createField("VALUE10", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>GET_IMPULSE_CNTV</code> table reference
     */
    public GetImpulseCntv() {
        this(DSL.name("GET_IMPULSE_CNTV"), null);
    }

    /**
     * Create an aliased <code>GET_IMPULSE_CNTV</code> table reference
     */
    public GetImpulseCntv(String alias) {
        this(DSL.name(alias), GET_IMPULSE_CNTV);
    }

    /**
     * Create an aliased <code>GET_IMPULSE_CNTV</code> table reference
     */
    public GetImpulseCntv(Name alias) {
        this(alias, GET_IMPULSE_CNTV);
    }

    private GetImpulseCntv(Name alias, Table<GetImpulseCntvRecord> aliased) {
        this(alias, aliased, new Field[2]);
    }

    private GetImpulseCntv(Name alias, Table<GetImpulseCntvRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GetImpulseCntv(Table<O> child, ForeignKey<O, GetImpulseCntvRecord> key) {
        super(child, key, GET_IMPULSE_CNTV);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntv as(String alias) {
        return new GetImpulseCntv(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntv as(Name alias) {
        return new GetImpulseCntv(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetImpulseCntv rename(String name) {
        return new GetImpulseCntv(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetImpulseCntv rename(Name name) {
        return new GetImpulseCntv(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetImpulseCntv call(String login, String pass) {
        return new GetImpulseCntv(DSL.name(getName()), null, new Field[] { 
              DSL.val(login, org.jooq.impl.SQLDataType.VARCHAR(32))
            , DSL.val(pass, org.jooq.impl.SQLDataType.VARCHAR(32))
        });
    }

    /**
     * Call this table-valued function
     */
    public GetImpulseCntv call(Field<String> login, Field<String> pass) {
        return new GetImpulseCntv(DSL.name(getName()), null, new Field[] { 
              login
            , pass
        });
    }
}
