/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.tables.records.GetImpulseCntvGazRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetImpulseCntvGaz extends TableImpl<GetImpulseCntvGazRecord> {

    private static final long serialVersionUID = -993621599;

    /**
     * The reference instance of <code>GET_IMPULSE_CNTV_GAZ</code>
     */
    public static final GetImpulseCntvGaz GET_IMPULSE_CNTV_GAZ = new GetImpulseCntvGaz();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GetImpulseCntvGazRecord> getRecordType() {
        return GetImpulseCntvGazRecord.class;
    }

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_ID</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Integer> CNT_ID = createField("CNT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.VALUE1</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> VALUE1 = createField("VALUE1", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.VALUE2</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> VALUE2 = createField("VALUE2", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.VALUE3</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> VALUE3 = createField("VALUE3", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.VALUE4</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> VALUE4 = createField("VALUE4", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.VALUE5</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> VALUE5 = createField("VALUE5", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CDATE</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Timestamp> CDATE = createField("CDATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.STATE</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Integer> STATE = createField("STATE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.VALUE6</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> VALUE6 = createField("VALUE6", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.VALUE7</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> VALUE7 = createField("VALUE7", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.VALUE8</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> VALUE8 = createField("VALUE8", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.VALUE9</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> VALUE9 = createField("VALUE9", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.VALUE10</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> VALUE10 = createField("VALUE10", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNTB_NAME</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, String> CNTB_NAME = createField("CNTB_NAME", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_SNUM</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, String> CNT_SNUM = createField("CNT_SNUM", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_NETADR</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, String> CNT_NETADR = createField("CNT_NETADR", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_ENTRY</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Integer> CNT_ENTRY = createField("CNT_ENTRY", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_NAME</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, String> CNT_NAME = createField("CNT_NAME", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_ADR</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, String> CNT_ADR = createField("CNT_ADR", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_TRANSFORMATION</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> CNT_TRANSFORMATION = createField("CNT_TRANSFORMATION", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_VALUE1</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> CNT_VALUE1 = createField("CNT_VALUE1", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_VALUE2</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> CNT_VALUE2 = createField("CNT_VALUE2", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_VALUE3</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Double> CNT_VALUE3 = createField("CNT_VALUE3", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_NUM_ABONENT</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, String> CNT_NUM_ABONENT = createField("CNT_NUM_ABONENT", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.REQUEST</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Integer> REQUEST = createField("REQUEST", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.USK_IP</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, String> USK_IP = createField("USK_IP", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.AB_NAME</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, String> AB_NAME = createField("AB_NAME", org.jooq.impl.SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.AB_ID</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Integer> AB_ID = createField("AB_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNTB_ID</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Integer> CNTB_ID = createField("CNTB_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_CORRECTION</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Integer> CNT_CORRECTION = createField("CNT_CORRECTION", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GET_IMPULSE_CNTV_GAZ.CNT_QTIME</code>.
     */
    public final TableField<GetImpulseCntvGazRecord, Integer> CNT_QTIME = createField("CNT_QTIME", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>GET_IMPULSE_CNTV_GAZ</code> table reference
     */
    public GetImpulseCntvGaz() {
        this(DSL.name("GET_IMPULSE_CNTV_GAZ"), null);
    }

    /**
     * Create an aliased <code>GET_IMPULSE_CNTV_GAZ</code> table reference
     */
    public GetImpulseCntvGaz(String alias) {
        this(DSL.name(alias), GET_IMPULSE_CNTV_GAZ);
    }

    /**
     * Create an aliased <code>GET_IMPULSE_CNTV_GAZ</code> table reference
     */
    public GetImpulseCntvGaz(Name alias) {
        this(alias, GET_IMPULSE_CNTV_GAZ);
    }

    private GetImpulseCntvGaz(Name alias, Table<GetImpulseCntvGazRecord> aliased) {
        this(alias, aliased, new Field[2]);
    }

    private GetImpulseCntvGaz(Name alias, Table<GetImpulseCntvGazRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GetImpulseCntvGaz(Table<O> child, ForeignKey<O, GetImpulseCntvGazRecord> key) {
        super(child, key, GET_IMPULSE_CNTV_GAZ);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvGaz as(String alias) {
        return new GetImpulseCntvGaz(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GetImpulseCntvGaz as(Name alias) {
        return new GetImpulseCntvGaz(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetImpulseCntvGaz rename(String name) {
        return new GetImpulseCntvGaz(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public GetImpulseCntvGaz rename(Name name) {
        return new GetImpulseCntvGaz(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public GetImpulseCntvGaz call(String login, String pass) {
        return new GetImpulseCntvGaz(DSL.name(getName()), null, new Field[] { 
              DSL.val(login, org.jooq.impl.SQLDataType.VARCHAR(32))
            , DSL.val(pass, org.jooq.impl.SQLDataType.VARCHAR(32))
        });
    }

    /**
     * Call this table-valued function
     */
    public GetImpulseCntvGaz call(Field<String> login, Field<String> pass) {
        return new GetImpulseCntvGaz(DSL.name(getName()), null, new Field[] { 
              login
            , pass
        });
    }
}
