/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.Keys;
import ru.smartsarov.citylighting.sprut.tables.records.GuardInformRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuardInform extends TableImpl<GuardInformRecord> {

    private static final long serialVersionUID = 1157945266;

    /**
     * The reference instance of <code>GUARD_INFORM</code>
     */
    public static final GuardInform GUARD_INFORM = new GuardInform();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuardInformRecord> getRecordType() {
        return GuardInformRecord.class;
    }

    /**
     * The column <code>GUARD_INFORM.GRDINF_ID</code>.
     */
    public final TableField<GuardInformRecord, Integer> GRDINF_ID = createField("GRDINF_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GUARD_INFORM.GRDINF_LOG_ID</code>.
     */
    public final TableField<GuardInformRecord, Integer> GRDINF_LOG_ID = createField("GRDINF_LOG_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GUARD_INFORM.GRDINF_DATETIME</code>.
     */
    public final TableField<GuardInformRecord, Timestamp> GRDINF_DATETIME = createField("GRDINF_DATETIME", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>GUARD_INFORM.GRDINF_NUM</code>.
     */
    public final TableField<GuardInformRecord, String> GRDINF_NUM = createField("GRDINF_NUM", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>GUARD_INFORM.GRDINF_NOTIFY</code>.
     */
    public final TableField<GuardInformRecord, Short> GRDINF_NOTIFY = createField("GRDINF_NOTIFY", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>GUARD_INFORM.GRDINF_TYPE</code>.
     */
    public final TableField<GuardInformRecord, Integer> GRDINF_TYPE = createField("GRDINF_TYPE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>GUARD_INFORM</code> table reference
     */
    public GuardInform() {
        this(DSL.name("GUARD_INFORM"), null);
    }

    /**
     * Create an aliased <code>GUARD_INFORM</code> table reference
     */
    public GuardInform(String alias) {
        this(DSL.name(alias), GUARD_INFORM);
    }

    /**
     * Create an aliased <code>GUARD_INFORM</code> table reference
     */
    public GuardInform(Name alias) {
        this(alias, GUARD_INFORM);
    }

    private GuardInform(Name alias, Table<GuardInformRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuardInform(Name alias, Table<GuardInformRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GuardInform(Table<O> child, ForeignKey<O, GuardInformRecord> key) {
        super(child, key, GUARD_INFORM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GuardInformRecord> getPrimaryKey() {
        return Keys.PK_GUARD_INFORM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GuardInformRecord>> getKeys() {
        return Arrays.<UniqueKey<GuardInformRecord>>asList(Keys.PK_GUARD_INFORM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardInform as(String alias) {
        return new GuardInform(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardInform as(Name alias) {
        return new GuardInform(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuardInform rename(String name) {
        return new GuardInform(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuardInform rename(Name name) {
        return new GuardInform(name, null);
    }
}
