/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.Keys;
import ru.smartsarov.citylighting.sprut.tables.records.GuardCamRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuardCam extends TableImpl<GuardCamRecord> {

    private static final long serialVersionUID = -2091335916;

    /**
     * The reference instance of <code>GUARD_CAM</code>
     */
    public static final GuardCam GUARD_CAM = new GuardCam();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuardCamRecord> getRecordType() {
        return GuardCamRecord.class;
    }

    /**
     * The column <code>GUARD_CAM.GRDC_ID</code>.
     */
    public final TableField<GuardCamRecord, Integer> GRDC_ID = createField("GRDC_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GUARD_CAM.GRDC_ZID</code>.
     */
    public final TableField<GuardCamRecord, Integer> GRDC_ZID = createField("GRDC_ZID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GUARD_CAM.GRDC_NAME</code>.
     */
    public final TableField<GuardCamRecord, String> GRDC_NAME = createField("GRDC_NAME", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>GUARD_CAM.GRDC_HOST</code>.
     */
    public final TableField<GuardCamRecord, String> GRDC_HOST = createField("GRDC_HOST", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>GUARD_CAM.GRDC_PASSWORD</code>.
     */
    public final TableField<GuardCamRecord, byte[]> GRDC_PASSWORD = createField("GRDC_PASSWORD", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * The column <code>GUARD_CAM.GRDC_CTYPE</code>.
     */
    public final TableField<GuardCamRecord, Integer> GRDC_CTYPE = createField("GRDC_CTYPE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GUARD_CAM.GRDC_ATYPE</code>.
     */
    public final TableField<GuardCamRecord, Integer> GRDC_ATYPE = createField("GRDC_ATYPE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GUARD_CAM.GRDC_ON</code>.
     */
    public final TableField<GuardCamRecord, Integer> GRDC_ON = createField("GRDC_ON", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GUARD_CAM.GRDC_USER</code>.
     */
    public final TableField<GuardCamRecord, String> GRDC_USER = createField("GRDC_USER", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * Create a <code>GUARD_CAM</code> table reference
     */
    public GuardCam() {
        this(DSL.name("GUARD_CAM"), null);
    }

    /**
     * Create an aliased <code>GUARD_CAM</code> table reference
     */
    public GuardCam(String alias) {
        this(DSL.name(alias), GUARD_CAM);
    }

    /**
     * Create an aliased <code>GUARD_CAM</code> table reference
     */
    public GuardCam(Name alias) {
        this(alias, GUARD_CAM);
    }

    private GuardCam(Name alias, Table<GuardCamRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuardCam(Name alias, Table<GuardCamRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GuardCam(Table<O> child, ForeignKey<O, GuardCamRecord> key) {
        super(child, key, GUARD_CAM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GuardCamRecord> getPrimaryKey() {
        return Keys.INTEG_63;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GuardCamRecord>> getKeys() {
        return Arrays.<UniqueKey<GuardCamRecord>>asList(Keys.INTEG_63);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardCam as(String alias) {
        return new GuardCam(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardCam as(Name alias) {
        return new GuardCam(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuardCam rename(String name) {
        return new GuardCam(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuardCam rename(Name name) {
        return new GuardCam(name, null);
    }
}
