/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.Keys;
import ru.smartsarov.citylighting.sprut.tables.records.GuardLsostRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuardLsost extends TableImpl<GuardLsostRecord> {

    private static final long serialVersionUID = 371497555;

    /**
     * The reference instance of <code>GUARD_LSOST</code>
     */
    public static final GuardLsost GUARD_LSOST = new GuardLsost();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuardLsostRecord> getRecordType() {
        return GuardLsostRecord.class;
    }

    /**
     * The column <code>GUARD_LSOST.GRDSL_ID</code>.
     */
    public final TableField<GuardLsostRecord, Integer> GRDSL_ID = createField("GRDSL_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GUARD_LSOST.GRDSL_NAME</code>.
     */
    public final TableField<GuardLsostRecord, String> GRDSL_NAME = createField("GRDSL_NAME", org.jooq.impl.SQLDataType.VARCHAR(16), this, "");

    /**
     * Create a <code>GUARD_LSOST</code> table reference
     */
    public GuardLsost() {
        this(DSL.name("GUARD_LSOST"), null);
    }

    /**
     * Create an aliased <code>GUARD_LSOST</code> table reference
     */
    public GuardLsost(String alias) {
        this(DSL.name(alias), GUARD_LSOST);
    }

    /**
     * Create an aliased <code>GUARD_LSOST</code> table reference
     */
    public GuardLsost(Name alias) {
        this(alias, GUARD_LSOST);
    }

    private GuardLsost(Name alias, Table<GuardLsostRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuardLsost(Name alias, Table<GuardLsostRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GuardLsost(Table<O> child, ForeignKey<O, GuardLsostRecord> key) {
        super(child, key, GUARD_LSOST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GuardLsostRecord> getPrimaryKey() {
        return Keys.INTEG_72;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GuardLsostRecord>> getKeys() {
        return Arrays.<UniqueKey<GuardLsostRecord>>asList(Keys.INTEG_72);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLsost as(String alias) {
        return new GuardLsost(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardLsost as(Name alias) {
        return new GuardLsost(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuardLsost rename(String name) {
        return new GuardLsost(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuardLsost rename(Name name) {
        return new GuardLsost(name, null);
    }
}
