/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.Keys;
import ru.smartsarov.citylighting.sprut.tables.records.GuardSmsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuardSms extends TableImpl<GuardSmsRecord> {

    private static final long serialVersionUID = -1717808580;

    /**
     * The reference instance of <code>GUARD_SMS</code>
     */
    public static final GuardSms GUARD_SMS = new GuardSms();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuardSmsRecord> getRecordType() {
        return GuardSmsRecord.class;
    }

    /**
     * The column <code>GUARD_SMS.GRDS_ID</code>.
     */
    public final TableField<GuardSmsRecord, Integer> GRDS_ID = createField("GRDS_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GUARD_SMS.GRDS_ZID</code>.
     */
    public final TableField<GuardSmsRecord, Integer> GRDS_ZID = createField("GRDS_ZID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GUARD_SMS.GRDS_NUM</code>.
     */
    public final TableField<GuardSmsRecord, String> GRDS_NUM = createField("GRDS_NUM", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>GUARD_SMS.GRDS_NAME</code>.
     */
    public final TableField<GuardSmsRecord, String> GRDS_NAME = createField("GRDS_NAME", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>GUARD_SMS.GRDS_ATYPE</code>.
     */
    public final TableField<GuardSmsRecord, Integer> GRDS_ATYPE = createField("GRDS_ATYPE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GUARD_SMS.GRDS_ON</code>.
     */
    public final TableField<GuardSmsRecord, Integer> GRDS_ON = createField("GRDS_ON", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>GUARD_SMS</code> table reference
     */
    public GuardSms() {
        this(DSL.name("GUARD_SMS"), null);
    }

    /**
     * Create an aliased <code>GUARD_SMS</code> table reference
     */
    public GuardSms(String alias) {
        this(DSL.name(alias), GUARD_SMS);
    }

    /**
     * Create an aliased <code>GUARD_SMS</code> table reference
     */
    public GuardSms(Name alias) {
        this(alias, GUARD_SMS);
    }

    private GuardSms(Name alias, Table<GuardSmsRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuardSms(Name alias, Table<GuardSmsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GuardSms(Table<O> child, ForeignKey<O, GuardSmsRecord> key) {
        super(child, key, GUARD_SMS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GuardSmsRecord> getPrimaryKey() {
        return Keys.INTEG_85;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GuardSmsRecord>> getKeys() {
        return Arrays.<UniqueKey<GuardSmsRecord>>asList(Keys.INTEG_85);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardSms as(String alias) {
        return new GuardSms(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardSms as(Name alias) {
        return new GuardSms(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuardSms rename(String name) {
        return new GuardSms(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuardSms rename(Name name) {
        return new GuardSms(name, null);
    }
}
