/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.Keys;
import ru.smartsarov.citylighting.sprut.tables.records.GuardSmsstatRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuardSmsstat extends TableImpl<GuardSmsstatRecord> {

    private static final long serialVersionUID = 1827553639;

    /**
     * The reference instance of <code>GUARD_SMSSTAT</code>
     */
    public static final GuardSmsstat GUARD_SMSSTAT = new GuardSmsstat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuardSmsstatRecord> getRecordType() {
        return GuardSmsstatRecord.class;
    }

    /**
     * The column <code>GUARD_SMSSTAT.GRDSMSST_ID</code>.
     */
    public final TableField<GuardSmsstatRecord, Integer> GRDSMSST_ID = createField("GRDSMSST_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GUARD_SMSSTAT.GRDSMSST_LOG_ID</code>.
     */
    public final TableField<GuardSmsstatRecord, Integer> GRDSMSST_LOG_ID = createField("GRDSMSST_LOG_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>GUARD_SMSSTAT.GRDSMSST_DATETIME</code>.
     */
    public final TableField<GuardSmsstatRecord, Timestamp> GRDSMSST_DATETIME = createField("GRDSMSST_DATETIME", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>GUARD_SMSSTAT.GRDSMSST_NUM</code>.
     */
    public final TableField<GuardSmsstatRecord, String> GRDSMSST_NUM = createField("GRDSMSST_NUM", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>GUARD_SMSSTAT.GRDSMSST_QUEUE</code>.
     */
    public final TableField<GuardSmsstatRecord, String> GRDSMSST_QUEUE = createField("GRDSMSST_QUEUE", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>GUARD_SMSSTAT.GRDSMSST_NOTIFY</code>.
     */
    public final TableField<GuardSmsstatRecord, Short> GRDSMSST_NOTIFY = createField("GRDSMSST_NOTIFY", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * Create a <code>GUARD_SMSSTAT</code> table reference
     */
    public GuardSmsstat() {
        this(DSL.name("GUARD_SMSSTAT"), null);
    }

    /**
     * Create an aliased <code>GUARD_SMSSTAT</code> table reference
     */
    public GuardSmsstat(String alias) {
        this(DSL.name(alias), GUARD_SMSSTAT);
    }

    /**
     * Create an aliased <code>GUARD_SMSSTAT</code> table reference
     */
    public GuardSmsstat(Name alias) {
        this(alias, GUARD_SMSSTAT);
    }

    private GuardSmsstat(Name alias, Table<GuardSmsstatRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuardSmsstat(Name alias, Table<GuardSmsstatRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GuardSmsstat(Table<O> child, ForeignKey<O, GuardSmsstatRecord> key) {
        super(child, key, GUARD_SMSSTAT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GuardSmsstatRecord> getPrimaryKey() {
        return Keys.GUARD_SMSSTAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GuardSmsstatRecord>> getKeys() {
        return Arrays.<UniqueKey<GuardSmsstatRecord>>asList(Keys.GUARD_SMSSTAT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardSmsstat as(String alias) {
        return new GuardSmsstat(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuardSmsstat as(Name alias) {
        return new GuardSmsstat(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuardSmsstat rename(String name) {
        return new GuardSmsstat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuardSmsstat rename(Name name) {
        return new GuardSmsstat(name, null);
    }
}
