/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.tables.records.Mon$contextVariablesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mon$contextVariables extends TableImpl<Mon$contextVariablesRecord> {

    private static final long serialVersionUID = -1326967675;

    /**
     * The reference instance of <code>MON$CONTEXT_VARIABLES</code>
     */
    public static final Mon$contextVariables MON$CONTEXT_VARIABLES = new Mon$contextVariables();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Mon$contextVariablesRecord> getRecordType() {
        return Mon$contextVariablesRecord.class;
    }

    /**
     * The column <code>MON$CONTEXT_VARIABLES.MON$ATTACHMENT_ID</code>.
     */
    public final TableField<Mon$contextVariablesRecord, Integer> MON$ATTACHMENT_ID = createField("MON$ATTACHMENT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MON$CONTEXT_VARIABLES.MON$TRANSACTION_ID</code>.
     */
    public final TableField<Mon$contextVariablesRecord, Integer> MON$TRANSACTION_ID = createField("MON$TRANSACTION_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>MON$CONTEXT_VARIABLES.MON$VARIABLE_NAME</code>.
     */
    public final TableField<Mon$contextVariablesRecord, String> MON$VARIABLE_NAME = createField("MON$VARIABLE_NAME", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>MON$CONTEXT_VARIABLES.MON$VARIABLE_VALUE</code>.
     */
    public final TableField<Mon$contextVariablesRecord, String> MON$VARIABLE_VALUE = createField("MON$VARIABLE_VALUE", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>MON$CONTEXT_VARIABLES</code> table reference
     */
    public Mon$contextVariables() {
        this(DSL.name("MON$CONTEXT_VARIABLES"), null);
    }

    /**
     * Create an aliased <code>MON$CONTEXT_VARIABLES</code> table reference
     */
    public Mon$contextVariables(String alias) {
        this(DSL.name(alias), MON$CONTEXT_VARIABLES);
    }

    /**
     * Create an aliased <code>MON$CONTEXT_VARIABLES</code> table reference
     */
    public Mon$contextVariables(Name alias) {
        this(alias, MON$CONTEXT_VARIABLES);
    }

    private Mon$contextVariables(Name alias, Table<Mon$contextVariablesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Mon$contextVariables(Name alias, Table<Mon$contextVariablesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Mon$contextVariables(Table<O> child, ForeignKey<O, Mon$contextVariablesRecord> key) {
        super(child, key, MON$CONTEXT_VARIABLES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Mon$contextVariables as(String alias) {
        return new Mon$contextVariables(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Mon$contextVariables as(Name alias) {
        return new Mon$contextVariables(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Mon$contextVariables rename(String name) {
        return new Mon$contextVariables(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Mon$contextVariables rename(Name name) {
        return new Mon$contextVariables(name, null);
    }
}
