/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.tables.records.ParseCntListRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParseCntList extends TableImpl<ParseCntListRecord> {

    private static final long serialVersionUID = 569778626;

    /**
     * The reference instance of <code>PARSE_CNT_LIST</code>
     */
    public static final ParseCntList PARSE_CNT_LIST = new ParseCntList();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ParseCntListRecord> getRecordType() {
        return ParseCntListRecord.class;
    }

    /**
     * The column <code>PARSE_CNT_LIST.CNT_ID</code>.
     */
    public final TableField<ParseCntListRecord, Integer> CNT_ID = createField("CNT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>PARSE_CNT_LIST</code> table reference
     */
    public ParseCntList() {
        this(DSL.name("PARSE_CNT_LIST"), null);
    }

    /**
     * Create an aliased <code>PARSE_CNT_LIST</code> table reference
     */
    public ParseCntList(String alias) {
        this(DSL.name(alias), PARSE_CNT_LIST);
    }

    /**
     * Create an aliased <code>PARSE_CNT_LIST</code> table reference
     */
    public ParseCntList(Name alias) {
        this(alias, PARSE_CNT_LIST);
    }

    private ParseCntList(Name alias, Table<ParseCntListRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private ParseCntList(Name alias, Table<ParseCntListRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ParseCntList(Table<O> child, ForeignKey<O, ParseCntListRecord> key) {
        super(child, key, PARSE_CNT_LIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParseCntList as(String alias) {
        return new ParseCntList(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ParseCntList as(Name alias) {
        return new ParseCntList(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public ParseCntList rename(String name) {
        return new ParseCntList(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public ParseCntList rename(Name name) {
        return new ParseCntList(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public ParseCntList call(String cntList) {
        return new ParseCntList(DSL.name(getName()), null, new Field[] { 
              DSL.val(cntList, org.jooq.impl.SQLDataType.VARCHAR(16384))
        });
    }

    /**
     * Call this table-valued function
     */
    public ParseCntList call(Field<String> cntList) {
        return new ParseCntList(DSL.name(getName()), null, new Field[] { 
              cntList
        });
    }
}
