/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.tables.records.Rdb$relationConstraintsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rdb$relationConstraints extends TableImpl<Rdb$relationConstraintsRecord> {

    private static final long serialVersionUID = -558154202;

    /**
     * The reference instance of <code>RDB$RELATION_CONSTRAINTS</code>
     */
    public static final Rdb$relationConstraints RDB$RELATION_CONSTRAINTS = new Rdb$relationConstraints();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Rdb$relationConstraintsRecord> getRecordType() {
        return Rdb$relationConstraintsRecord.class;
    }

    /**
     * The column <code>RDB$RELATION_CONSTRAINTS.RDB$CONSTRAINT_NAME</code>.
     */
    public final TableField<Rdb$relationConstraintsRecord, String> RDB$CONSTRAINT_NAME = createField("RDB$CONSTRAINT_NAME", org.jooq.impl.SQLDataType.CHAR, this, "");

    /**
     * The column <code>RDB$RELATION_CONSTRAINTS.RDB$CONSTRAINT_TYPE</code>.
     */
    public final TableField<Rdb$relationConstraintsRecord, String> RDB$CONSTRAINT_TYPE = createField("RDB$CONSTRAINT_TYPE", org.jooq.impl.SQLDataType.CHAR, this, "");

    /**
     * The column <code>RDB$RELATION_CONSTRAINTS.RDB$RELATION_NAME</code>.
     */
    public final TableField<Rdb$relationConstraintsRecord, String> RDB$RELATION_NAME = createField("RDB$RELATION_NAME", org.jooq.impl.SQLDataType.CHAR, this, "");

    /**
     * The column <code>RDB$RELATION_CONSTRAINTS.RDB$DEFERRABLE</code>.
     */
    public final TableField<Rdb$relationConstraintsRecord, String> RDB$DEFERRABLE = createField("RDB$DEFERRABLE", org.jooq.impl.SQLDataType.CHAR, this, "");

    /**
     * The column <code>RDB$RELATION_CONSTRAINTS.RDB$INITIALLY_DEFERRED</code>.
     */
    public final TableField<Rdb$relationConstraintsRecord, String> RDB$INITIALLY_DEFERRED = createField("RDB$INITIALLY_DEFERRED", org.jooq.impl.SQLDataType.CHAR, this, "");

    /**
     * The column <code>RDB$RELATION_CONSTRAINTS.RDB$INDEX_NAME</code>.
     */
    public final TableField<Rdb$relationConstraintsRecord, String> RDB$INDEX_NAME = createField("RDB$INDEX_NAME", org.jooq.impl.SQLDataType.CHAR, this, "");

    /**
     * Create a <code>RDB$RELATION_CONSTRAINTS</code> table reference
     */
    public Rdb$relationConstraints() {
        this(DSL.name("RDB$RELATION_CONSTRAINTS"), null);
    }

    /**
     * Create an aliased <code>RDB$RELATION_CONSTRAINTS</code> table reference
     */
    public Rdb$relationConstraints(String alias) {
        this(DSL.name(alias), RDB$RELATION_CONSTRAINTS);
    }

    /**
     * Create an aliased <code>RDB$RELATION_CONSTRAINTS</code> table reference
     */
    public Rdb$relationConstraints(Name alias) {
        this(alias, RDB$RELATION_CONSTRAINTS);
    }

    private Rdb$relationConstraints(Name alias, Table<Rdb$relationConstraintsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Rdb$relationConstraints(Name alias, Table<Rdb$relationConstraintsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Rdb$relationConstraints(Table<O> child, ForeignKey<O, Rdb$relationConstraintsRecord> key) {
        super(child, key, RDB$RELATION_CONSTRAINTS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Rdb$relationConstraints as(String alias) {
        return new Rdb$relationConstraints(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Rdb$relationConstraints as(Name alias) {
        return new Rdb$relationConstraints(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rdb$relationConstraints rename(String name) {
        return new Rdb$relationConstraints(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rdb$relationConstraints rename(Name name) {
        return new Rdb$relationConstraints(name, null);
    }
}
