/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.Keys;
import ru.smartsarov.citylighting.sprut.tables.records.UskExtChangeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UskExtChange extends TableImpl<UskExtChangeRecord> {

    private static final long serialVersionUID = -611616262;

    /**
     * The reference instance of <code>USK_EXT_CHANGE</code>
     */
    public static final UskExtChange USK_EXT_CHANGE = new UskExtChange();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UskExtChangeRecord> getRecordType() {
        return UskExtChangeRecord.class;
    }

    /**
     * The column <code>USK_EXT_CHANGE.USKEC_ID</code>.
     */
    public final TableField<UskExtChangeRecord, Integer> USKEC_ID = createField("USKEC_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>USK_EXT_CHANGE.USKEC_USK_EXT_ID</code>.
     */
    public final TableField<UskExtChangeRecord, Integer> USKEC_USK_EXT_ID = createField("USKEC_USK_EXT_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>USK_EXT_CHANGE.USKEC_TYPE</code>.
     */
    public final TableField<UskExtChangeRecord, Integer> USKEC_TYPE = createField("USKEC_TYPE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USK_EXT_CHANGE.USKEC_XUSER_ID</code>.
     */
    public final TableField<UskExtChangeRecord, Integer> USKEC_XUSER_ID = createField("USKEC_XUSER_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USK_EXT_CHANGE.USKEC_DATE</code>.
     */
    public final TableField<UskExtChangeRecord, Timestamp> USKEC_DATE = createField("USKEC_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>USK_EXT_CHANGE</code> table reference
     */
    public UskExtChange() {
        this(DSL.name("USK_EXT_CHANGE"), null);
    }

    /**
     * Create an aliased <code>USK_EXT_CHANGE</code> table reference
     */
    public UskExtChange(String alias) {
        this(DSL.name(alias), USK_EXT_CHANGE);
    }

    /**
     * Create an aliased <code>USK_EXT_CHANGE</code> table reference
     */
    public UskExtChange(Name alias) {
        this(alias, USK_EXT_CHANGE);
    }

    private UskExtChange(Name alias, Table<UskExtChangeRecord> aliased) {
        this(alias, aliased, null);
    }

    private UskExtChange(Name alias, Table<UskExtChangeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UskExtChange(Table<O> child, ForeignKey<O, UskExtChangeRecord> key) {
        super(child, key, USK_EXT_CHANGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UskExtChangeRecord> getPrimaryKey() {
        return Keys.INTEG_98;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UskExtChangeRecord>> getKeys() {
        return Arrays.<UniqueKey<UskExtChangeRecord>>asList(Keys.INTEG_98);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtChange as(String alias) {
        return new UskExtChange(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UskExtChange as(Name alias) {
        return new UskExtChange(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UskExtChange rename(String name) {
        return new UskExtChange(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UskExtChange rename(Name name) {
        return new UskExtChange(name, null);
    }
}
