/*
 * This file is generated by jOOQ.
 */
package ru.smartsarov.citylighting.sprut.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.smartsarov.citylighting.sprut.DefaultSchema;
import ru.smartsarov.citylighting.sprut.tables.records.UsklSyncRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsklSync extends TableImpl<UsklSyncRecord> {

    private static final long serialVersionUID = -877810680;

    /**
     * The reference instance of <code>USKL_SYNC</code>
     */
    public static final UsklSync USKL_SYNC = new UsklSync();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsklSyncRecord> getRecordType() {
        return UsklSyncRecord.class;
    }

    /**
     * The column <code>USKL_SYNC.USKL_ID</code>.
     */
    public final TableField<UsklSyncRecord, Integer> USKL_ID = createField("USKL_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>USKL_SYNC.USKL_LASTS_ID</code>.
     */
    public final TableField<UsklSyncRecord, Integer> USKL_LASTS_ID = createField("USKL_LASTS_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USKL_SYNC.USKL_STATE</code>.
     */
    public final TableField<UsklSyncRecord, Integer> USKL_STATE = createField("USKL_STATE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USKL_SYNC.USKL_LAST_TIME</code>.
     */
    public final TableField<UsklSyncRecord, Timestamp> USKL_LAST_TIME = createField("USKL_LAST_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>USKL_SYNC</code> table reference
     */
    public UsklSync() {
        this(DSL.name("USKL_SYNC"), null);
    }

    /**
     * Create an aliased <code>USKL_SYNC</code> table reference
     */
    public UsklSync(String alias) {
        this(DSL.name(alias), USKL_SYNC);
    }

    /**
     * Create an aliased <code>USKL_SYNC</code> table reference
     */
    public UsklSync(Name alias) {
        this(alias, USKL_SYNC);
    }

    private UsklSync(Name alias, Table<UsklSyncRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsklSync(Name alias, Table<UsklSyncRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UsklSync(Table<O> child, ForeignKey<O, UsklSyncRecord> key) {
        super(child, key, USKL_SYNC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsklSync as(String alias) {
        return new UsklSync(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsklSync as(Name alias) {
        return new UsklSync(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsklSync rename(String name) {
        return new UsklSync(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsklSync rename(Name name) {
        return new UsklSync(name, null);
    }
}
